/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentRegistry,
  IAgentRegistryInterface,
} from "../../../contracts/interfaces/IAgentRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "endpoint",
        type: "string",
      },
    ],
    name: "AgentRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "enum IAgentRegistry.AgentStatus",
        name: "oldStatus",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "enum IAgentRegistry.AgentStatus",
        name: "newStatus",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "AgentStatusChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "field",
        type: "string",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "newValue",
        type: "bytes",
      },
    ],
    name: "AgentUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "capabilityId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "name",
        type: "string",
      },
    ],
    name: "CapabilityDeclared",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "oldScore",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newScore",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "transactionId",
        type: "bytes32",
      },
    ],
    name: "TrustScoreUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "blacklistAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
    ],
    name: "deactivateAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "capabilityId",
            type: "bytes32",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "version",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "schemaHash",
            type: "bytes32",
          },
        ],
        internalType: "struct IAgentRegistry.CapabilityDeclaration",
        name: "capability",
        type: "tuple",
      },
    ],
    name: "declareCapability",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "capabilityId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "minTrustScore",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
    ],
    name: "findAgentsByCapability",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "agentIds",
        type: "bytes32[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
    ],
    name: "getAgent",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "agentId",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "address",
            name: "paymentWallet",
            type: "address",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "endpoint",
            type: "string",
          },
          {
            internalType: "bytes32[]",
            name: "capabilities",
            type: "bytes32[]",
          },
          {
            internalType: "uint256",
            name: "trustScore",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalTransactions",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalVolume",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "registeredAt",
            type: "uint256",
          },
          {
            internalType: "enum IAgentRegistry.AgentStatus",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct IAgentRegistry.AgentInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "getAgentByWallet",
    outputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
    ],
    name: "getAgentCapabilities",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "",
        type: "bytes32[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
    ],
    name: "getAgentStatus",
    outputs: [
      {
        internalType: "enum IAgentRegistry.AgentStatus",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "capabilityId",
        type: "bytes32",
      },
    ],
    name: "hasCapability",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
    ],
    name: "isAgentActive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "endpoint",
        type: "string",
      },
      {
        internalType: "address",
        name: "paymentWallet",
        type: "address",
      },
      {
        internalType: "bytes32[]",
        name: "capabilities",
        type: "bytes32[]",
      },
    ],
    name: "registerAgent",
    outputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
    ],
    name: "reinstateAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "suspendAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "endpoint",
        type: "string",
      },
      {
        internalType: "address",
        name: "paymentWallet",
        type: "address",
      },
    ],
    name: "updateAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "transactionId",
        type: "bytes32",
      },
      {
        internalType: "int256",
        name: "scoreChange",
        type: "int256",
      },
    ],
    name: "updateTrustScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAgentRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentRegistryInterface {
    return new Interface(_abi) as IAgentRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentRegistry {
    return new Contract(address, _abi, runner) as unknown as IAgentRegistry;
  }
}
