/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICollaboration,
  ICollaborationInterface,
} from "../../../contracts/interfaces/ICollaboration";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "activatedAt",
        type: "uint256",
      },
    ],
    name: "AgreementActivated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "approver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "currentApprovals",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "requiredApprovals",
        type: "uint8",
      },
    ],
    name: "AgreementApproved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "initiator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32[]",
        name: "agentIds",
        type: "bytes32[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "validUntil",
        type: "uint256",
      },
    ],
    name: "AgreementCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "terminator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "AgreementTerminated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "transactionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "distributions",
        type: "uint256[]",
      },
    ],
    name: "ShareDistributed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
    ],
    name: "approveAgreement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "totalAmount",
        type: "uint256",
      },
    ],
    name: "calculateDistribution",
    outputs: [
      {
        internalType: "uint256[]",
        name: "distributions",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "agentIds",
        type: "bytes32[]",
      },
      {
        internalType: "address[]",
        name: "agentWallets",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "shareRatios",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "validUntil",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "termsHash",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "requiredApprovals",
        type: "uint8",
      },
    ],
    name: "createAgreement",
    outputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "templateId",
        type: "bytes32",
      },
      {
        internalType: "bytes32[]",
        name: "agentIds",
        type: "bytes32[]",
      },
      {
        internalType: "address[]",
        name: "agentWallets",
        type: "address[]",
      },
      {
        internalType: "uint256",
        name: "validUntil",
        type: "uint256",
      },
    ],
    name: "createFromTemplate",
    outputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "uint256[]",
        name: "defaultRatios",
        type: "uint256[]",
      },
      {
        internalType: "bytes32",
        name: "termsHash",
        type: "bytes32",
      },
    ],
    name: "createTemplate",
    outputs: [
      {
        internalType: "bytes32",
        name: "templateId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "totalAmount",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "transactionId",
        type: "bytes32",
      },
    ],
    name: "distributeByAgreement",
    outputs: [
      {
        internalType: "uint256[]",
        name: "distributions",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "newValidUntil",
        type: "uint256",
      },
    ],
    name: "extendAgreement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
    ],
    name: "getAgentAgreements",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "",
        type: "bytes32[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
    ],
    name: "getAgreement",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "agreementId",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "initiator",
            type: "address",
          },
          {
            internalType: "bytes32[]",
            name: "agentIds",
            type: "bytes32[]",
          },
          {
            internalType: "address[]",
            name: "agentWallets",
            type: "address[]",
          },
          {
            internalType: "uint256[]",
            name: "shareRatios",
            type: "uint256[]",
          },
          {
            internalType: "uint256",
            name: "validFrom",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "validUntil",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "termsHash",
            type: "bytes32",
          },
          {
            internalType: "uint8",
            name: "requiredApprovals",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "currentApprovals",
            type: "uint8",
          },
          {
            internalType: "enum ICollaboration.AgreementStatus",
            name: "status",
            type: "uint8",
          },
        ],
        internalType: "struct ICollaboration.Agreement",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
    ],
    name: "getAgreementStatus",
    outputs: [
      {
        internalType: "enum ICollaboration.AgreementStatus",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "approver",
        type: "address",
      },
    ],
    name: "hasApproved",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
    ],
    name: "isAgreementValid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "agreementId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "terminateAgreement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICollaboration__factory {
  static readonly abi = _abi;
  static createInterface(): ICollaborationInterface {
    return new Interface(_abi) as ICollaborationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICollaboration {
    return new Contract(address, _abi, runner) as unknown as ICollaboration;
  }
}
