#!/bin/bash
# 后端部署脚本

echo "=== 1. 打包后端代码 ==="
cd backend
tar -czf ../backend.tar.gz --exclude=node_modules --exclude=dist --exclude=.git --exclude='*.log' .
echo "✅ 打包完成: backend.tar.gz"

echo ""
echo "=== 2. 上传到服务器 ==="
echo "请执行以下命令上传文件："
echo "scp backend.tar.gz root@129.226.152.88:/tmp/"

echo ""
echo "=== 3. 在服务器上执行以下命令（复制粘贴到服务器） ==="
echo ""
echo "# 连接到服务器"
echo "ssh root@129.226.152.88"
echo ""
echo "# 进入后端目录（重要！必须先切换目录）"
echo "cd /var/www/agentrix-website/backend"
echo ""
echo "# 停止服务"
echo "pm2 stop agentrix-backend"
echo ""
echo "# 备份当前代码"
echo "BACKUP_DIR=\"/var/www/agentrix-website-backup-\$(date +%Y%m%d-%H%M%S)\""
echo "mkdir -p \"\$BACKUP_DIR\""
echo "cp -r . \"\$BACKUP_DIR/\" 2>/dev/null || true"
echo "echo \"备份已保存到: \$BACKUP_DIR\""
echo ""
echo "# 清理旧文件（保留 node_modules 和 dist，稍后重新构建）"
echo "rm -rf src scripts *.ts *.json *.md .env 2>/dev/null || true"
echo ""
echo "# 解压新代码"
echo "tar -xzf /tmp/backend.tar.gz"
echo ""
echo "# 安装依赖"
echo "echo \"安装依赖...\""
echo "npm install"
echo ""
echo "# 构建项目"
echo "echo \"构建项目...\""
echo "npm run build"
echo ""
echo "# 验证构建"
echo "if [ ! -f \"dist/main.js\" ]; then"
echo "    echo \"❌ 构建失败: dist/main.js 不存在\""
echo "    exit 1"
echo "fi"
echo ""
echo "# 运行数据库迁移"
echo "echo \"运行数据库迁移...\""
echo "npm run migration:run"
echo ""
echo "# 重启服务"
echo "pm2 restart agentrix-backend --update-env"
echo ""
echo "# 查看服务状态"
echo "pm2 status"
echo ""
echo "# 查看日志"
echo "echo \"\""
echo "echo \"=== 最近 20 行日志 ===\""
echo "pm2 logs agentrix-backend --lines 20 --nostream"

