-- Fix Commerce Database: Create missing tables and add missing columns
-- Generated by ARCHITECT-01

-- ========== 1. Create ENUM types ==========
DO $$ BEGIN
  CREATE TYPE "commerce_order_status_enum" AS ENUM('draft', 'pending', 'paid', 'fulfilled', 'cancelled', 'refunded');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "commerce_order_type_enum" AS ENUM('product', 'service', 'subscription');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "commerce_settlement_status_enum" AS ENUM('pending', 'processing', 'paid', 'failed');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "ledger_entry_type_enum" AS ENUM('order_created', 'payment_captured', 'refund', 'payout', 'commission', 'adjustment');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- ========== 2. Create commerce_orders table ==========
CREATE TABLE IF NOT EXISTS "commerce_orders" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "user_id" varchar NOT NULL,
  "type" "commerce_order_type_enum" NOT NULL DEFAULT 'product',
  "status" "commerce_order_status_enum" NOT NULL DEFAULT 'draft',
  "amount" decimal(18,2) NOT NULL,
  "currency" varchar(10) NOT NULL DEFAULT 'USD',
  "items" jsonb NOT NULL DEFAULT '[]',
  "split_plan_id" varchar,
  "payment_intent_id" varchar,
  "metadata" jsonb,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_commerce_orders" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "IDX_commerce_orders_user_id" ON "commerce_orders" ("user_id");
CREATE INDEX IF NOT EXISTS "IDX_commerce_orders_user_status" ON "commerce_orders" ("user_id", "status");
CREATE INDEX IF NOT EXISTS "IDX_commerce_orders_status_created" ON "commerce_orders" ("status", "created_at");

-- ========== 3. Create commerce_settlements table ==========
CREATE TABLE IF NOT EXISTS "commerce_settlements" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "order_id" varchar NOT NULL,
  "split_plan_id" varchar,
  "total_amount" decimal(18,2) NOT NULL,
  "currency" varchar(10) NOT NULL DEFAULT 'USD',
  "platform_fee" decimal(18,2) NOT NULL DEFAULT 0,
  "net_amount" decimal(18,2) NOT NULL DEFAULT 0,
  "allocations" jsonb NOT NULL DEFAULT '[]',
  "status" "commerce_settlement_status_enum" NOT NULL DEFAULT 'pending',
  "paid_by" varchar,
  "paid_at" timestamptz,
  "metadata" jsonb,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_commerce_settlements" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "IDX_commerce_settlements_order" ON "commerce_settlements" ("order_id");
CREATE INDEX IF NOT EXISTS "IDX_commerce_settlements_status" ON "commerce_settlements" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "IDX_commerce_settlements_split" ON "commerce_settlements" ("split_plan_id");

-- ========== 4. Create commerce_ledger table ==========
CREATE TABLE IF NOT EXISTS "commerce_ledger" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "type" "ledger_entry_type_enum" NOT NULL,
  "user_id" varchar,
  "order_id" varchar,
  "settlement_id" varchar,
  "recipient_id" varchar,
  "amount" decimal(18,2) NOT NULL,
  "currency" varchar(10) NOT NULL DEFAULT 'USD',
  "reason" varchar,
  "tx_hash" varchar,
  "metadata" jsonb,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "PK_commerce_ledger" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "IDX_commerce_ledger_user_type" ON "commerce_ledger" ("user_id", "type");
CREATE INDEX IF NOT EXISTS "IDX_commerce_ledger_order" ON "commerce_ledger" ("order_id");
CREATE INDEX IF NOT EXISTS "IDX_commerce_ledger_type_created" ON "commerce_ledger" ("type", "created_at");
CREATE INDEX IF NOT EXISTS "IDX_commerce_ledger_created" ON "commerce_ledger" ("created_at");

-- ========== 5. Add missing blockchain columns to budget_pools ==========
ALTER TABLE "budget_pools" ADD COLUMN IF NOT EXISTS "onchain_pool_id" integer;
ALTER TABLE "budget_pools" ADD COLUMN IF NOT EXISTS "fund_tx_hash" varchar;

-- ========== 6. Add missing blockchain columns to milestones ==========
ALTER TABLE "milestones" ADD COLUMN IF NOT EXISTS "onchain_milestone_id" integer;
ALTER TABLE "milestones" ADD COLUMN IF NOT EXISTS "release_tx_hash" varchar;

-- ========== 7. Verify ==========
SELECT 'commerce_orders' as tbl, count(*) as rows FROM commerce_orders
UNION ALL
SELECT 'commerce_settlements', count(*) FROM commerce_settlements
UNION ALL
SELECT 'commerce_ledger', count(*) FROM commerce_ledger
UNION ALL
SELECT 'budget_pools', count(*) FROM budget_pools
UNION ALL
SELECT 'milestones', count(*) FROM milestones
UNION ALL
SELECT 'split_plans', count(*) FROM split_plans;
