import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateMerchantProfile1765538849744 implements MigrationInterface {
    name = 'CreateMerchantProfile1765538849744'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Migration skipped due to permission issues and existing tables
        return Promise.resolve();
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "api_keys" DROP CONSTRAINT "FK_a3baee01d8408cd3c0f89a9a973"`);
        await queryRunner.query(`ALTER TABLE "merchant_profiles" DROP CONSTRAINT "FK_8177c1c1fafa1d05177b9a45329"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP CONSTRAINT "FK_a2ffe4b13d499c0e8aa165996c6"`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" DROP CONSTRAINT "FK_4fb7acafe990a5abbf321c534a5"`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" DROP CONSTRAINT "FK_48a6cbf3db98bc76347a8ff4615"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66fd180e7e0ee1ac31f003bcba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9caabe7c3a8dabd16e206879b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9bdba9200942bb473313764db9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cef5ce7c595db3ef0126a9ad65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10ae0181853fe5ddf3372bccba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_128772fbda0ab3bf2605f2955d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_827af7fe090efe8ee13c98c384"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_316e4c34c7b75742e11c083f89"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0c7f32fe3dea54c9818e5dd96"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca680c529b18e7b957df5121c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0361b2c9c65f76e59b7fd3d7b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a20cec9b80e97a87d2259da5d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4cb9b00e587d37247b0ede91b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48a6cbf3db98bc76347a8ff461"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7bf8ade89ec9a566493f3f5e8"`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" ALTER COLUMN "riskFactors" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "risk_assessments"."riskScore" IS NULL`);
        await queryRunner.query(`ALTER TABLE "commission_settlements" ALTER COLUMN "payeeType" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."commissions_payeetype_enum_old" AS ENUM('agent', 'agentrix', 'merchant')`);
        await queryRunner.query(`ALTER TABLE "commission_settlements" ALTER COLUMN "payeeType" TYPE "public"."commissions_payeetype_enum_old" USING "payeeType"::"text"::"public"."commissions_payeetype_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."commission_settlements_payeetype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."commissions_payeetype_enum_old" RENAME TO "commissions_payeetype_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."commissions_payeetype_enum_old" AS ENUM('agent', 'agentrix', 'merchant')`);
        await queryRunner.query(`ALTER TABLE "commissions" ALTER COLUMN "payeeType" TYPE "public"."commissions_payeetype_enum_old" USING "payeeType"::"text"::"public"."commissions_payeetype_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."commissions_payeetype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."commissions_payeetype_enum_old" RENAME TO "commissions_payeetype_enum"`);
        await queryRunner.query(`ALTER TABLE "merchant_referrals" ALTER COLUMN "commissionRate" SET DEFAULT 0.005`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ALTER COLUMN "submitted_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_sync_mappings" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "product_sync_mappings" DROP COLUMN "sync_direction"`);
        await queryRunner.query(`ALTER TABLE "product_sync_mappings" ADD "sync_direction" character varying(20) NOT NULL DEFAULT 'import'`);
        await queryRunner.query(`ALTER TABLE "product_sync_mappings" DROP COLUMN "external_product_id"`);
        await queryRunner.query(`ALTER TABLE "product_sync_mappings" ADD "external_product_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ecommerce_connections" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ecommerce_connections" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ecommerce_connections" DROP COLUMN "store_url"`);
        await queryRunner.query(`ALTER TABLE "ecommerce_connections" ADD "store_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "ecommerce_connections" DROP COLUMN "store_name"`);
        await queryRunner.query(`ALTER TABLE "ecommerce_connections" ADD "store_name" character varying(255) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum_old" AS ENUM('active', 'inactive', 'out_of_stock')`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "status" TYPE "public"."products_status_enum_old" USING "status"::"text"::"public"."products_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."products_status_enum_old" RENAME TO "products_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."payments_paymentmethod_enum_old" AS ENUM('epay', 'multisig', 'passkey', 'stripe', 'wallet', 'x402')`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "paymentMethod" TYPE "public"."payments_paymentmethod_enum_old" USING "paymentMethod"::"text"::"public"."payments_paymentmethod_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."payments_paymentmethod_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payments_paymentmethod_enum_old" RENAME TO "payments_paymentmethod_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "roles"`);
        await queryRunner.query(`CREATE TYPE "public"."users_roles_enum" AS ENUM('agent', 'merchant', 'user')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "roles" "public"."users_roles_enum" array NOT NULL DEFAULT '{user}'`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" DROP COLUMN "agentId"`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" DROP COLUMN "transactionId"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "lastSyncedAt"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "usdValue"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "balance"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "tokenSymbol"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "tokenAddress"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "incomeMode"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "commissionRate"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "tokenId"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "contractAddress"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "sourceType"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "sourcePlatform"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "assetType"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" DROP COLUMN "assetId"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "autoReviewResult"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "revisionFields"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "rejectionReason"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "reviewComment"`);
        await queryRunner.query(`ALTER TABLE "product_reviews" DROP COLUMN "productSnapshot"`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" DROP COLUMN "decision"`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" DROP COLUMN "paymentId"`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" ADD "metadata" jsonb`);
        await queryRunner.query(`CREATE TYPE "public"."risk_assessments_decision_enum" AS ENUM('approve', 'reject', 'review')`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" ADD "decision" "public"."risk_assessments_decision_enum" DEFAULT 'review'`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" ADD "paymentId" uuid`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "assetId" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "currency" character varying(3)`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "tokenId" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "contractAddress" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "sourcePlatform" character varying(100) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."asset_aggregations_incomemode_enum" AS ENUM('platform_commission', 'user_paid')`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "incomeMode" "public"."asset_aggregations_incomemode_enum"`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "commissionRate" numeric(5,4)`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "price" numeric(18,2)`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "metadata" jsonb`);
        await queryRunner.query(`CREATE TYPE "public"."asset_aggregations_sourcetype_enum" AS ENUM('platform_aggregated', 'user_generated')`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "sourceType" "public"."asset_aggregations_sourcetype_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."asset_aggregations_assettype_enum" AS ENUM('ft', 'game_asset', 'nft', 'rwa')`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "assetType" "public"."asset_aggregations_assettype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "tokenSymbol" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "tokenAddress" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "lastSyncedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "usdValue" numeric(18,2)`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "balance" numeric(18,6) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_aggregations" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "rejection_reason" text`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "review_comment" text`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "auto_review_result" jsonb`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "revision_fields" jsonb`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD "product_snapshot" jsonb`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" ADD "agentId" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" ADD "transactionId" uuid`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57384430aa1959f4578046c9b8"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP TYPE "public"."api_keys_status_enum"`);
        await queryRunner.query(`DROP TABLE "merchant_profiles"`);
        await queryRunner.query(`CREATE INDEX "IDX_48a6cbf3db98bc76347a8ff461" ON "risk_assessments" ("paymentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7bf8ade89ec9a566493f3f5e8" ON "risk_assessments" ("createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cef5ce7c595db3ef0126a9ad65" ON "asset_aggregations" ("chain", "assetId", "sourcePlatform") `);
        await queryRunner.query(`CREATE INDEX "IDX_10ae0181853fe5ddf3372bccba" ON "asset_aggregations" ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_128772fbda0ab3bf2605f2955d" ON "asset_aggregations" ("assetType") `);
        await queryRunner.query(`CREATE INDEX "IDX_827af7fe090efe8ee13c98c384" ON "asset_aggregations" ("sourcePlatform") `);
        await queryRunner.query(`CREATE INDEX "IDX_316e4c34c7b75742e11c083f89" ON "asset_aggregations" ("sourceType") `);
        await queryRunner.query(`CREATE INDEX "IDX_9caabe7c3a8dabd16e206879b0" ON "asset_aggregations" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9bdba9200942bb473313764db9" ON "asset_aggregations" ("chain", "tokenAddress") `);
        await queryRunner.query(`CREATE INDEX "IDX_product_reviews_merchant_status" ON "product_reviews" ("merchant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_product_reviews_product_status" ON "product_reviews" ("product_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_product_sync_mappings_product_id" ON "product_sync_mappings" ("product_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_product_sync_mappings_connection_external_unique" ON "product_sync_mappings" ("connection_id", "external_product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ecommerce_connections_merchant_platform" ON "ecommerce_connections" ("merchant_id", "platform") `);
        await queryRunner.query(`CREATE INDEX "IDX_66fd180e7e0ee1ac31f003bcba" ON "risk_assessments" ("transactionId") `);
        await queryRunner.query(`ALTER TABLE "risk_assessments" ADD CONSTRAINT "FK_48a6cbf3db98bc76347a8ff4615" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_assessments" ADD CONSTRAINT "FK_4fb7acafe990a5abbf321c534a5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_reviews" ADD CONSTRAINT "FK_a2ffe4b13d499c0e8aa165996c6" FOREIGN KEY ("reviewer_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
