import { MigrationInterface, QueryRunner } from 'typeorm';

export class FixSessionHandoffSessionIdType1774772000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Change sessionId from UUID to VARCHAR(100) to support non-UUID session IDs
    // like "session-1774667905139" generated by mobile/desktop clients
    await queryRunner.query(`
      ALTER TABLE "session_handoffs"
        ALTER COLUMN "session_id" TYPE VARCHAR(100)
        USING "session_id"::text;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DELETE FROM "session_handoffs"
        WHERE "session_id" IS NOT NULL
          AND "session_id" !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';
    `);
    await queryRunner.query(`
      ALTER TABLE "session_handoffs"
        ALTER COLUMN "session_id" TYPE UUID
        USING "session_id"::uuid;
    `);
  }
}
