/**
 * Agent 页面共享类型定义
 */

export type ViewMode =
  | 'chat'
  | 'marketplace'
  | 'autoEarn'
  | 'cart'
  | 'code'
  | 'sandbox'
  | 'orders'
  | 'order'
  | 'settings'
  | 'referral'
  | 'wallet'
  | 'wallet_management'
  | 'payment_assistant'
  | 'policies'
  | 'airdrops'
  | 'authorizations'
  | 'profile'
  | 'security'
  | 'merchant_orders'
  | 'merchant_products'
  | 'merchant_ecommerce'
  | 'merchant_batch'
  | 'merchant_mpc'
  | 'merchant_finance'
  | 'merchant_api'
  | 'merchant_api_keys'
  | 'merchant_webhooks'
  | 'merchant_analytics'
  | 'merchant_audit'
  | 'merchant_settings'
  | 'sdk_generator'
  | 'api_assistant'
  | 'devops'
  | 'logs'
  | 'user_module'
  | 'merchant_module'
  | 'developer_module'
  | 'unified_workbench';


