/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReceiptRegistry {
  export type ReceiptStruct = {
    paymentId: BytesLike;
    payer: AddressLike;
    merchant: AddressLike;
    agent: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    protocolFee: BigNumberish;
    timestamp: BigNumberish;
    epochId: BigNumberish;
    routeRefHash: BytesLike;
  };

  export type ReceiptStructOutput = [
    paymentId: string,
    payer: string,
    merchant: string,
    agent: string,
    token: string,
    amount: bigint,
    protocolFee: bigint,
    timestamp: bigint,
    epochId: bigint,
    routeRefHash: string
  ] & {
    paymentId: string;
    payer: string;
    merchant: string;
    agent: string;
    token: string;
    amount: bigint;
    protocolFee: bigint;
    timestamp: bigint;
    epochId: bigint;
    routeRefHash: string;
  };
}

export interface ReceiptRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "EMITTER_ROLE"
      | "epochReceipts"
      | "epochTotalFees"
      | "epochTotalVolume"
      | "getEpochReceiptIds"
      | "getEpochStats"
      | "getReceipt"
      | "getRoleAdmin"
      | "getTotalReceipts"
      | "grantRole"
      | "hasRole"
      | "receiptIds"
      | "receipts"
      | "recordReceipt"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EpochFinalized"
      | "ReceiptCreated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMITTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochReceipts",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochTotalFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochTotalVolume",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEpochReceiptIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEpochStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceipt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalReceipts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiptIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "receipts", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "recordReceipt",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMITTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochReceipts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochTotalFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochTotalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEpochReceiptIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEpochStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReceipt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalReceipts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "receiptIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "receipts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace EpochFinalizedEvent {
  export type InputTuple = [
    epochId: BigNumberish,
    totalReceipts: BigNumberish,
    totalVolume: BigNumberish,
    totalFees: BigNumberish
  ];
  export type OutputTuple = [
    epochId: bigint,
    totalReceipts: bigint,
    totalVolume: bigint,
    totalFees: bigint
  ];
  export interface OutputObject {
    epochId: bigint;
    totalReceipts: bigint;
    totalVolume: bigint;
    totalFees: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptCreatedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    payer: AddressLike,
    merchant: AddressLike,
    agent: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    protocolFee: BigNumberish,
    epochId: BigNumberish,
    routeRefHash: BytesLike
  ];
  export type OutputTuple = [
    paymentId: string,
    payer: string,
    merchant: string,
    agent: string,
    token: string,
    amount: bigint,
    protocolFee: bigint,
    epochId: bigint,
    routeRefHash: string
  ];
  export interface OutputObject {
    paymentId: string;
    payer: string;
    merchant: string;
    agent: string;
    token: string;
    amount: bigint;
    protocolFee: bigint;
    epochId: bigint;
    routeRefHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReceiptRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReceiptRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReceiptRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EMITTER_ROLE: TypedContractMethod<[], [string], "view">;

  epochReceipts: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  epochTotalFees: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  epochTotalVolume: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEpochReceiptIds: TypedContractMethod<
    [epochId: BigNumberish],
    [string[]],
    "view"
  >;

  getEpochStats: TypedContractMethod<
    [epochId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        totalReceipts: bigint;
        totalVolume: bigint;
        totalFees: bigint;
      }
    ],
    "view"
  >;

  getReceipt: TypedContractMethod<
    [paymentId: BytesLike],
    [ReceiptRegistry.ReceiptStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTotalReceipts: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  receiptIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  receipts: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        paymentId: string;
        payer: string;
        merchant: string;
        agent: string;
        token: string;
        amount: bigint;
        protocolFee: bigint;
        timestamp: bigint;
        epochId: bigint;
        routeRefHash: string;
      }
    ],
    "view"
  >;

  recordReceipt: TypedContractMethod<
    [
      paymentId: BytesLike,
      payer: AddressLike,
      merchant: AddressLike,
      agent: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      protocolFee: BigNumberish,
      epochId: BigNumberish,
      routeRefHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EMITTER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "epochReceipts"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "epochTotalFees"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "epochTotalVolume"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEpochReceiptIds"
  ): TypedContractMethod<[epochId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEpochStats"
  ): TypedContractMethod<
    [epochId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        totalReceipts: bigint;
        totalVolume: bigint;
        totalFees: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceipt"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [ReceiptRegistry.ReceiptStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalReceipts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiptIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "receipts"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        paymentId: string;
        payer: string;
        merchant: string;
        agent: string;
        token: string;
        amount: bigint;
        protocolFee: bigint;
        timestamp: bigint;
        epochId: bigint;
        routeRefHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordReceipt"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      payer: AddressLike,
      merchant: AddressLike,
      agent: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      protocolFee: BigNumberish,
      epochId: BigNumberish,
      routeRefHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "EpochFinalized"
  ): TypedContractEvent<
    EpochFinalizedEvent.InputTuple,
    EpochFinalizedEvent.OutputTuple,
    EpochFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptCreated"
  ): TypedContractEvent<
    ReceiptCreatedEvent.InputTuple,
    ReceiptCreatedEvent.OutputTuple,
    ReceiptCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "EpochFinalized(uint256,uint256,uint256,uint256)": TypedContractEvent<
      EpochFinalizedEvent.InputTuple,
      EpochFinalizedEvent.OutputTuple,
      EpochFinalizedEvent.OutputObject
    >;
    EpochFinalized: TypedContractEvent<
      EpochFinalizedEvent.InputTuple,
      EpochFinalizedEvent.OutputTuple,
      EpochFinalizedEvent.OutputObject
    >;

    "ReceiptCreated(bytes32,address,address,address,address,uint256,uint256,uint256,bytes32)": TypedContractEvent<
      ReceiptCreatedEvent.InputTuple,
      ReceiptCreatedEvent.OutputTuple,
      ReceiptCreatedEvent.OutputObject
    >;
    ReceiptCreated: TypedContractEvent<
      ReceiptCreatedEvent.InputTuple,
      ReceiptCreatedEvent.OutputTuple,
      ReceiptCreatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
