/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AuditProof {
  export type TaskConfigStruct = {
    taskId: BytesLike;
    creator: AddressLike;
    executor: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    platformFee: BigNumberish;
    mode: BigNumberish;
    expectedProofHash: BytesLike;
    requiredSignatures: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    deadline: BigNumberish;
    releasedAt: BigNumberish;
    submittedResultHash: BytesLike;
    qualityScore: BigNumberish;
  };

  export type TaskConfigStructOutput = [
    taskId: string,
    creator: string,
    executor: string,
    token: string,
    amount: bigint,
    platformFee: bigint,
    mode: bigint,
    expectedProofHash: string,
    requiredSignatures: bigint,
    status: bigint,
    createdAt: bigint,
    deadline: bigint,
    releasedAt: bigint,
    submittedResultHash: string,
    qualityScore: bigint
  ] & {
    taskId: string;
    creator: string;
    executor: string;
    token: string;
    amount: bigint;
    platformFee: bigint;
    mode: bigint;
    expectedProofHash: string;
    requiredSignatures: bigint;
    status: bigint;
    createdAt: bigint;
    deadline: bigint;
    releasedAt: bigint;
    submittedResultHash: string;
    qualityScore: bigint;
  };

  export type SignatureRecordStruct = {
    signer: AddressLike;
    resultHash: BytesLike;
    quality: BigNumberish;
    timestamp: BigNumberish;
  };

  export type SignatureRecordStructOutput = [
    signer: string,
    resultHash: string,
    quality: bigint,
    timestamp: bigint
  ] & {
    signer: string;
    resultHash: string;
    quality: bigint;
    timestamp: bigint;
  };
}

export interface AuditProofInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_WINDOW"
      | "MAX_AUDITORS"
      | "MIN_QUALITY_SCORE"
      | "RELEASE_TYPEHASH"
      | "confirmRelease"
      | "createTask"
      | "defaultPlatformFeeRate"
      | "disputeTask"
      | "eip712Domain"
      | "emergencyWithdraw"
      | "fundTask"
      | "getTask"
      | "getTaskAuditors"
      | "getTaskSignatures"
      | "hasSignedTask"
      | "isAuditorForTask"
      | "nonce"
      | "owner"
      | "pause"
      | "paused"
      | "platformTreasury"
      | "refundExpired"
      | "renounceOwnership"
      | "resolveDispute"
      | "setDefaultPlatformFeeRate"
      | "setPlatformTreasury"
      | "setTrustedAuditor"
      | "submitResult"
      | "taskAuditors"
      | "taskSignatures"
      | "tasks"
      | "transferOwnership"
      | "trustedAuditors"
      | "unpause"
      | "verifyResult"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditorUpdated"
      | "EIP712DomainChanged"
      | "FundsReleased"
      | "OwnershipTransferred"
      | "Paused"
      | "ProofVerified"
      | "ResultSubmitted"
      | "TaskCreated"
      | "TaskDisputed"
      | "TaskFunded"
      | "TaskRefunded"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_AUDITORS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_QUALITY_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELEASE_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confirmRelease",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      AddressLike[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultPlatformFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTask",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fundTask", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getTask", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getTaskAuditors",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskSignatures",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSignedTask",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuditorForTask",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundExpired",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultPlatformFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedAuditor",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResult",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "taskAuditors",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "taskSignatures",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedAuditors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyResult",
    values: [BytesLike, BytesLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_AUDITORS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_QUALITY_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELEASE_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultPlatformFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTaskAuditors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTaskSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSignedTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuditorForTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultPlatformFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedAuditor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskAuditors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedAuditors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyResult",
    data: BytesLike
  ): Result;
}

export namespace AuditorUpdatedEvent {
  export type InputTuple = [auditor: AddressLike, trusted: boolean];
  export type OutputTuple = [auditor: string, trusted: boolean];
  export interface OutputObject {
    auditor: string;
    trusted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    executor: AddressLike,
    amount: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    executor: string,
    amount: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    taskId: string;
    executor: string;
    amount: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofVerifiedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    auditor: AddressLike,
    resultHash: BytesLike,
    quality: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    auditor: string,
    resultHash: string,
    quality: bigint
  ];
  export interface OutputObject {
    taskId: string;
    auditor: string;
    resultHash: string;
    quality: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultSubmittedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    executor: AddressLike,
    resultHash: BytesLike
  ];
  export type OutputTuple = [
    taskId: string,
    executor: string,
    resultHash: string
  ];
  export interface OutputObject {
    taskId: string;
    executor: string;
    resultHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    creator: AddressLike,
    executor: AddressLike,
    amount: BigNumberish,
    mode: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    creator: string,
    executor: string,
    amount: bigint,
    mode: bigint
  ];
  export interface OutputObject {
    taskId: string;
    creator: string;
    executor: string;
    amount: bigint;
    mode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDisputedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    disputer: AddressLike,
    reason: string
  ];
  export type OutputTuple = [taskId: string, disputer: string, reason: string];
  export interface OutputObject {
    taskId: string;
    disputer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskFundedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    funder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: string, funder: string, amount: bigint];
  export interface OutputObject {
    taskId: string;
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskRefundedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: string, creator: string, amount: bigint];
  export interface OutputObject {
    taskId: string;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuditProof extends BaseContract {
  connect(runner?: ContractRunner | null): AuditProof;
  waitForDeployment(): Promise<this>;

  interface: AuditProofInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  MAX_AUDITORS: TypedContractMethod<[], [bigint], "view">;

  MIN_QUALITY_SCORE: TypedContractMethod<[], [bigint], "view">;

  RELEASE_TYPEHASH: TypedContractMethod<[], [string], "view">;

  confirmRelease: TypedContractMethod<
    [taskId: BytesLike, quality: BigNumberish],
    [void],
    "nonpayable"
  >;

  createTask: TypedContractMethod<
    [
      taskId: BytesLike,
      executor: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      mode: BigNumberish,
      expectedProofHash: BytesLike,
      auditors: AddressLike[],
      requiredSignatures: BigNumberish,
      deadline: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  defaultPlatformFeeRate: TypedContractMethod<[], [bigint], "view">;

  disputeTask: TypedContractMethod<
    [taskId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundTask: TypedContractMethod<[taskId: BytesLike], [void], "payable">;

  getTask: TypedContractMethod<
    [taskId: BytesLike],
    [AuditProof.TaskConfigStructOutput],
    "view"
  >;

  getTaskAuditors: TypedContractMethod<[taskId: BytesLike], [string[]], "view">;

  getTaskSignatures: TypedContractMethod<
    [taskId: BytesLike],
    [AuditProof.SignatureRecordStructOutput[]],
    "view"
  >;

  hasSignedTask: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isAuditorForTask: TypedContractMethod<
    [taskId: BytesLike, auditor: AddressLike],
    [boolean],
    "view"
  >;

  nonce: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  refundExpired: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [
      taskId: BytesLike,
      releaseToExecutor: boolean,
      executorShare: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setDefaultPlatformFeeRate: TypedContractMethod<
    [rate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformTreasury: TypedContractMethod<
    [treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setTrustedAuditor: TypedContractMethod<
    [auditor: AddressLike, trusted: boolean],
    [void],
    "nonpayable"
  >;

  submitResult: TypedContractMethod<
    [taskId: BytesLike, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;

  taskAuditors: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  taskSignatures: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        signer: string;
        resultHash: string;
        quality: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  tasks: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        taskId: string;
        creator: string;
        executor: string;
        token: string;
        amount: bigint;
        platformFee: bigint;
        mode: bigint;
        expectedProofHash: string;
        requiredSignatures: bigint;
        status: bigint;
        createdAt: bigint;
        deadline: bigint;
        releasedAt: bigint;
        submittedResultHash: string;
        qualityScore: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedAuditors: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyResult: TypedContractMethod<
    [
      taskId: BytesLike,
      resultHash: BytesLike,
      quality: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_AUDITORS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_QUALITY_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RELEASE_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "confirmRelease"
  ): TypedContractMethod<
    [taskId: BytesLike, quality: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      executor: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      mode: BigNumberish,
      expectedProofHash: BytesLike,
      auditors: AddressLike[],
      requiredSignatures: BigNumberish,
      deadline: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultPlatformFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputeTask"
  ): TypedContractMethod<
    [taskId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [AuditProof.TaskConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTaskAuditors"
  ): TypedContractMethod<[taskId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTaskSignatures"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [AuditProof.SignatureRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasSignedTask"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuditorForTask"
  ): TypedContractMethod<
    [taskId: BytesLike, auditor: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundExpired"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      releaseToExecutor: boolean,
      executorShare: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDefaultPlatformFeeRate"
  ): TypedContractMethod<[rate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformTreasury"
  ): TypedContractMethod<[treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTrustedAuditor"
  ): TypedContractMethod<
    [auditor: AddressLike, trusted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitResult"
  ): TypedContractMethod<
    [taskId: BytesLike, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskAuditors"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "taskSignatures"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        signer: string;
        resultHash: string;
        quality: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        taskId: string;
        creator: string;
        executor: string;
        token: string;
        amount: bigint;
        platformFee: bigint;
        mode: bigint;
        expectedProofHash: string;
        requiredSignatures: bigint;
        status: bigint;
        createdAt: bigint;
        deadline: bigint;
        releasedAt: bigint;
        submittedResultHash: string;
        qualityScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedAuditors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyResult"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      resultHash: BytesLike,
      quality: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuditorUpdated"
  ): TypedContractEvent<
    AuditorUpdatedEvent.InputTuple,
    AuditorUpdatedEvent.OutputTuple,
    AuditorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProofVerified"
  ): TypedContractEvent<
    ProofVerifiedEvent.InputTuple,
    ProofVerifiedEvent.OutputTuple,
    ProofVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "ResultSubmitted"
  ): TypedContractEvent<
    ResultSubmittedEvent.InputTuple,
    ResultSubmittedEvent.OutputTuple,
    ResultSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDisputed"
  ): TypedContractEvent<
    TaskDisputedEvent.InputTuple,
    TaskDisputedEvent.OutputTuple,
    TaskDisputedEvent.OutputObject
  >;
  getEvent(
    key: "TaskFunded"
  ): TypedContractEvent<
    TaskFundedEvent.InputTuple,
    TaskFundedEvent.OutputTuple,
    TaskFundedEvent.OutputObject
  >;
  getEvent(
    key: "TaskRefunded"
  ): TypedContractEvent<
    TaskRefundedEvent.InputTuple,
    TaskRefundedEvent.OutputTuple,
    TaskRefundedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AuditorUpdated(address,bool)": TypedContractEvent<
      AuditorUpdatedEvent.InputTuple,
      AuditorUpdatedEvent.OutputTuple,
      AuditorUpdatedEvent.OutputObject
    >;
    AuditorUpdated: TypedContractEvent<
      AuditorUpdatedEvent.InputTuple,
      AuditorUpdatedEvent.OutputTuple,
      AuditorUpdatedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "FundsReleased(bytes32,address,uint256,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProofVerified(bytes32,address,bytes32,uint256)": TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
    ProofVerified: TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;

    "ResultSubmitted(bytes32,address,bytes32)": TypedContractEvent<
      ResultSubmittedEvent.InputTuple,
      ResultSubmittedEvent.OutputTuple,
      ResultSubmittedEvent.OutputObject
    >;
    ResultSubmitted: TypedContractEvent<
      ResultSubmittedEvent.InputTuple,
      ResultSubmittedEvent.OutputTuple,
      ResultSubmittedEvent.OutputObject
    >;

    "TaskCreated(bytes32,address,address,uint256,uint8)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskDisputed(bytes32,address,string)": TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;
    TaskDisputed: TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;

    "TaskFunded(bytes32,address,uint256)": TypedContractEvent<
      TaskFundedEvent.InputTuple,
      TaskFundedEvent.OutputTuple,
      TaskFundedEvent.OutputObject
    >;
    TaskFunded: TypedContractEvent<
      TaskFundedEvent.InputTuple,
      TaskFundedEvent.OutputTuple,
      TaskFundedEvent.OutputObject
    >;

    "TaskRefunded(bytes32,address,uint256)": TypedContractEvent<
      TaskRefundedEvent.InputTuple,
      TaskRefundedEvent.OutputTuple,
      TaskRefundedEvent.OutputObject
    >;
    TaskRefunded: TypedContractEvent<
      TaskRefundedEvent.InputTuple,
      TaskRefundedEvent.OutputTuple,
      TaskRefundedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
