/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AutoPay {
  export type AutoPaymentStruct = {
    paymentId: BytesLike;
    user: AddressLike;
    agent: AddressLike;
    recipient: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
    executed: boolean;
  };

  export type AutoPaymentStructOutput = [
    paymentId: string,
    user: string,
    agent: string,
    recipient: string,
    amount: bigint,
    timestamp: bigint,
    executed: boolean
  ] & {
    paymentId: string;
    user: string;
    agent: string;
    recipient: string;
    amount: bigint;
    timestamp: bigint;
    executed: boolean;
  };

  export type GrantStruct = {
    user: AddressLike;
    agent: AddressLike;
    singleLimit: BigNumberish;
    dailyLimit: BigNumberish;
    usedToday: BigNumberish;
    lastResetDate: BigNumberish;
    expiresAt: BigNumberish;
    isActive: boolean;
  };

  export type GrantStructOutput = [
    user: string,
    agent: string,
    singleLimit: bigint,
    dailyLimit: bigint,
    usedToday: bigint,
    lastResetDate: bigint,
    expiresAt: bigint,
    isActive: boolean
  ] & {
    user: string;
    agent: string;
    singleLimit: bigint;
    dailyLimit: bigint;
    usedToday: bigint;
    lastResetDate: bigint;
    expiresAt: bigint;
    isActive: boolean;
  };
}

export interface AutoPayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "autoPayments"
      | "createGrant"
      | "emergencyWithdraw"
      | "executeAutoPayment"
      | "getAutoPayment"
      | "getGrant"
      | "grants"
      | "owner"
      | "pause"
      | "paused"
      | "paymentToken"
      | "renounceOwnership"
      | "revokeGrant"
      | "setPaymentToken"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutoPaymentExecuted"
      | "GrantCreated"
      | "GrantRevoked"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "autoPayments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createGrant",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAutoPayment",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAutoPayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGrant",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grants",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeGrant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "autoPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeAutoPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAutoPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGrant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grants", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace AutoPaymentExecutedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    user: AddressLike,
    agent: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    user: string,
    agent: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    user: string;
    agent: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GrantCreatedEvent {
  export type InputTuple = [
    user: AddressLike,
    agent: AddressLike,
    singleLimit: BigNumberish,
    dailyLimit: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    agent: string,
    singleLimit: bigint,
    dailyLimit: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    user: string;
    agent: string;
    singleLimit: bigint;
    dailyLimit: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GrantRevokedEvent {
  export type InputTuple = [user: AddressLike, agent: AddressLike];
  export type OutputTuple = [user: string, agent: string];
  export interface OutputObject {
    user: string;
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AutoPay extends BaseContract {
  connect(runner?: ContractRunner | null): AutoPay;
  waitForDeployment(): Promise<this>;

  interface: AutoPayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  autoPayments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        paymentId: string;
        user: string;
        agent: string;
        recipient: string;
        amount: bigint;
        timestamp: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  createGrant: TypedContractMethod<
    [
      agent: AddressLike,
      singleLimit: BigNumberish,
      dailyLimit: BigNumberish,
      duration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeAutoPayment: TypedContractMethod<
    [
      paymentId: BytesLike,
      user: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getAutoPayment: TypedContractMethod<
    [paymentId: BytesLike],
    [AutoPay.AutoPaymentStructOutput],
    "view"
  >;

  getGrant: TypedContractMethod<
    [user: AddressLike, agent: AddressLike],
    [AutoPay.GrantStructOutput],
    "view"
  >;

  grants: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        user: string;
        agent: string;
        singleLimit: bigint;
        dailyLimit: bigint;
        usedToday: bigint;
        lastResetDate: bigint;
        expiresAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeGrant: TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;

  setPaymentToken: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "autoPayments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        paymentId: string;
        user: string;
        agent: string;
        recipient: string;
        amount: bigint;
        timestamp: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createGrant"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      singleLimit: BigNumberish,
      dailyLimit: BigNumberish,
      duration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeAutoPayment"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      user: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAutoPayment"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [AutoPay.AutoPaymentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGrant"
  ): TypedContractMethod<
    [user: AddressLike, agent: AddressLike],
    [AutoPay.GrantStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grants"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        user: string;
        agent: string;
        singleLimit: bigint;
        dailyLimit: bigint;
        usedToday: bigint;
        lastResetDate: bigint;
        expiresAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeGrant"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaymentToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AutoPaymentExecuted"
  ): TypedContractEvent<
    AutoPaymentExecutedEvent.InputTuple,
    AutoPaymentExecutedEvent.OutputTuple,
    AutoPaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "GrantCreated"
  ): TypedContractEvent<
    GrantCreatedEvent.InputTuple,
    GrantCreatedEvent.OutputTuple,
    GrantCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GrantRevoked"
  ): TypedContractEvent<
    GrantRevokedEvent.InputTuple,
    GrantRevokedEvent.OutputTuple,
    GrantRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AutoPaymentExecuted(bytes32,address,address,address,uint256)": TypedContractEvent<
      AutoPaymentExecutedEvent.InputTuple,
      AutoPaymentExecutedEvent.OutputTuple,
      AutoPaymentExecutedEvent.OutputObject
    >;
    AutoPaymentExecuted: TypedContractEvent<
      AutoPaymentExecutedEvent.InputTuple,
      AutoPaymentExecutedEvent.OutputTuple,
      AutoPaymentExecutedEvent.OutputObject
    >;

    "GrantCreated(address,address,uint256,uint256,uint256)": TypedContractEvent<
      GrantCreatedEvent.InputTuple,
      GrantCreatedEvent.OutputTuple,
      GrantCreatedEvent.OutputObject
    >;
    GrantCreated: TypedContractEvent<
      GrantCreatedEvent.InputTuple,
      GrantCreatedEvent.OutputTuple,
      GrantCreatedEvent.OutputObject
    >;

    "GrantRevoked(address,address)": TypedContractEvent<
      GrantRevokedEvent.InputTuple,
      GrantRevokedEvent.OutputTuple,
      GrantRevokedEvent.OutputObject
    >;
    GrantRevoked: TypedContractEvent<
      GrantRevokedEvent.InputTuple,
      GrantRevokedEvent.OutputTuple,
      GrantRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
