/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BudgetPool {
  export type QualityGateStruct = {
    minQualityScore: BigNumberish;
    requiresApproval: boolean;
    autoReleaseDelay: BigNumberish;
  };

  export type QualityGateStructOutput = [
    minQualityScore: bigint,
    requiresApproval: boolean,
    autoReleaseDelay: bigint
  ] & {
    minQualityScore: bigint;
    requiresApproval: boolean;
    autoReleaseDelay: bigint;
  };

  export type MilestoneStruct = {
    milestoneId: BytesLike;
    poolId: BytesLike;
    title: string;
    description: string;
    budgetAmount: BigNumberish;
    percentOfPool: BigNumberish;
    status: BigNumberish;
    participants: AddressLike[];
    participantShares: BigNumberish[];
    deliverableHash: BytesLike;
    submittedAt: BigNumberish;
    approvedAt: BigNumberish;
    approver: AddressLike;
    qualityScore: BigNumberish;
  };

  export type MilestoneStructOutput = [
    milestoneId: string,
    poolId: string,
    title: string,
    description: string,
    budgetAmount: bigint,
    percentOfPool: bigint,
    status: bigint,
    participants: string[],
    participantShares: bigint[],
    deliverableHash: string,
    submittedAt: bigint,
    approvedAt: bigint,
    approver: string,
    qualityScore: bigint
  ] & {
    milestoneId: string;
    poolId: string;
    title: string;
    description: string;
    budgetAmount: bigint;
    percentOfPool: bigint;
    status: bigint;
    participants: string[];
    participantShares: bigint[];
    deliverableHash: string;
    submittedAt: bigint;
    approvedAt: bigint;
    approver: string;
    qualityScore: bigint;
  };

  export type ParticipantStruct = {
    wallet: AddressLike;
    totalEarned: BigNumberish;
    pendingAmount: BigNumberish;
    claimedAmount: BigNumberish;
  };

  export type ParticipantStructOutput = [
    wallet: string,
    totalEarned: bigint,
    pendingAmount: bigint,
    claimedAmount: bigint
  ] & {
    wallet: string;
    totalEarned: bigint;
    pendingAmount: bigint;
    claimedAmount: bigint;
  };

  export type PoolStruct = {
    poolId: BytesLike;
    owner: AddressLike;
    name: string;
    description: string;
    totalBudget: BigNumberish;
    fundedAmount: BigNumberish;
    reservedAmount: BigNumberish;
    releasedAmount: BigNumberish;
    token: AddressLike;
    status: BigNumberish;
    createdAt: BigNumberish;
    deadline: BigNumberish;
  };

  export type PoolStructOutput = [
    poolId: string,
    owner: string,
    name: string,
    description: string,
    totalBudget: bigint,
    fundedAmount: bigint,
    reservedAmount: bigint,
    releasedAmount: bigint,
    token: string,
    status: bigint,
    createdAt: bigint,
    deadline: bigint
  ] & {
    poolId: string;
    owner: string;
    name: string;
    description: string;
    totalBudget: bigint;
    fundedAmount: bigint;
    reservedAmount: bigint;
    releasedAmount: bigint;
    token: string;
    status: bigint;
    createdAt: bigint;
    deadline: bigint;
  };
}

export interface BudgetPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "MAX_MILESTONES"
      | "MIN_POOL_AMOUNT"
      | "activatePool"
      | "addApprover"
      | "allPoolIds"
      | "approveMilestone"
      | "claim"
      | "createMilestone"
      | "createPool"
      | "fundPool"
      | "getMilestone"
      | "getOwnerPools"
      | "getParticipant"
      | "getPendingBalance"
      | "getPool"
      | "getPoolMilestones"
      | "getQualityGate"
      | "milestones"
      | "operators"
      | "owner"
      | "ownerPools"
      | "pause"
      | "paused"
      | "pendingBalances"
      | "platformFeeBps"
      | "platformTreasury"
      | "poolApprovers"
      | "poolMilestones"
      | "poolParticipants"
      | "poolQualityGates"
      | "pools"
      | "rejectMilestone"
      | "releaseMilestoneFunds"
      | "removeApprover"
      | "renounceOwnership"
      | "setOperator"
      | "setPlatformFee"
      | "setPlatformTreasury"
      | "settlementToken"
      | "startMilestone"
      | "submitMilestone"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsReleased"
      | "MilestoneApproved"
      | "MilestoneCreated"
      | "MilestoneRejected"
      | "MilestoneStatusChanged"
      | "MilestoneSubmitted"
      | "OperatorUpdated"
      | "OwnershipTransferred"
      | "ParticipantPaid"
      | "Paused"
      | "PoolCreated"
      | "PoolFunded"
      | "PoolStatusChanged"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_MILESTONES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_POOL_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activatePool",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addApprover",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allPoolIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveMilestone",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createMilestone",
    values: [
      BytesLike,
      string,
      string,
      BigNumberish,
      AddressLike[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BudgetPool.QualityGateStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fundPool",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestone",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerPools",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipant",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getPool", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getPoolMilestones",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getQualityGate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "milestones",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerPools",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolApprovers",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolMilestones",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "poolParticipants",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolQualityGates",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pools", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "rejectMilestone",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseMilestoneFunds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeApprover",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startMilestone",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitMilestone",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_MILESTONES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_POOL_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activatePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addApprover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allPoolIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolMilestones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQualityGate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "milestones", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerPools", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolApprovers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolMilestones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolQualityGates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestoneFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeApprover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    milestoneId: BytesLike,
    totalAmount: BigNumberish,
    participantCount: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: string,
    totalAmount: bigint,
    participantCount: bigint
  ];
  export interface OutputObject {
    milestoneId: string;
    totalAmount: bigint;
    participantCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneApprovedEvent {
  export type InputTuple = [
    milestoneId: BytesLike,
    approver: AddressLike,
    qualityScore: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: string,
    approver: string,
    qualityScore: bigint
  ];
  export interface OutputObject {
    milestoneId: string;
    approver: string;
    qualityScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneCreatedEvent {
  export type InputTuple = [
    milestoneId: BytesLike,
    poolId: BytesLike,
    title: string,
    budgetAmount: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: string,
    poolId: string,
    title: string,
    budgetAmount: bigint
  ];
  export interface OutputObject {
    milestoneId: string;
    poolId: string;
    title: string;
    budgetAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneRejectedEvent {
  export type InputTuple = [
    milestoneId: BytesLike,
    approver: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    milestoneId: string,
    approver: string,
    reason: string
  ];
  export interface OutputObject {
    milestoneId: string;
    approver: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneStatusChangedEvent {
  export type InputTuple = [
    milestoneId: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: string,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    milestoneId: string;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneSubmittedEvent {
  export type InputTuple = [
    milestoneId: BytesLike,
    deliverableHash: BytesLike,
    submitter: AddressLike
  ];
  export type OutputTuple = [
    milestoneId: string,
    deliverableHash: string,
    submitter: string
  ];
  export interface OutputObject {
    milestoneId: string;
    deliverableHash: string;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorUpdatedEvent {
  export type InputTuple = [operator: AddressLike, authorized: boolean];
  export type OutputTuple = [operator: string, authorized: boolean];
  export interface OutputObject {
    operator: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantPaidEvent {
  export type InputTuple = [
    milestoneId: BytesLike,
    participant: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: string,
    participant: string,
    amount: bigint
  ];
  export interface OutputObject {
    milestoneId: string;
    participant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    owner: AddressLike,
    name: string,
    totalBudget: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    poolId: string,
    owner: string,
    name: string,
    totalBudget: bigint,
    token: string
  ];
  export interface OutputObject {
    poolId: string;
    owner: string;
    name: string;
    totalBudget: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolFundedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    funder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: string, funder: string, amount: bigint];
  export interface OutputObject {
    poolId: string;
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolStatusChangedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    poolId: string;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BudgetPool extends BaseContract {
  connect(runner?: ContractRunner | null): BudgetPool;
  waitForDeployment(): Promise<this>;

  interface: BudgetPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  MAX_MILESTONES: TypedContractMethod<[], [bigint], "view">;

  MIN_POOL_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  activatePool: TypedContractMethod<[_poolId: BytesLike], [void], "nonpayable">;

  addApprover: TypedContractMethod<
    [_poolId: BytesLike, _approver: AddressLike],
    [void],
    "nonpayable"
  >;

  allPoolIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  approveMilestone: TypedContractMethod<
    [_milestoneId: BytesLike, _qualityScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<[], [void], "nonpayable">;

  createMilestone: TypedContractMethod<
    [
      _poolId: BytesLike,
      _title: string,
      _description: string,
      _percentOfPool: BigNumberish,
      _participants: AddressLike[],
      _shares: BigNumberish[]
    ],
    [string],
    "nonpayable"
  >;

  createPool: TypedContractMethod<
    [
      _name: string,
      _description: string,
      _totalBudget: BigNumberish,
      _deadline: BigNumberish,
      _qualityGate: BudgetPool.QualityGateStruct
    ],
    [string],
    "nonpayable"
  >;

  fundPool: TypedContractMethod<
    [_poolId: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getMilestone: TypedContractMethod<
    [_milestoneId: BytesLike],
    [BudgetPool.MilestoneStructOutput],
    "view"
  >;

  getOwnerPools: TypedContractMethod<[_owner: AddressLike], [string[]], "view">;

  getParticipant: TypedContractMethod<
    [_poolId: BytesLike, _participant: AddressLike],
    [BudgetPool.ParticipantStructOutput],
    "view"
  >;

  getPendingBalance: TypedContractMethod<
    [_account: AddressLike],
    [bigint],
    "view"
  >;

  getPool: TypedContractMethod<
    [_poolId: BytesLike],
    [BudgetPool.PoolStructOutput],
    "view"
  >;

  getPoolMilestones: TypedContractMethod<
    [_poolId: BytesLike],
    [string[]],
    "view"
  >;

  getQualityGate: TypedContractMethod<
    [_poolId: BytesLike],
    [BudgetPool.QualityGateStructOutput],
    "view"
  >;

  milestones: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        milestoneId: string;
        poolId: string;
        title: string;
        description: string;
        budgetAmount: bigint;
        percentOfPool: bigint;
        status: bigint;
        deliverableHash: string;
        submittedAt: bigint;
        approvedAt: bigint;
        approver: string;
        qualityScore: bigint;
      }
    ],
    "view"
  >;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerPools: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  poolApprovers: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  poolMilestones: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  poolParticipants: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        wallet: string;
        totalEarned: bigint;
        pendingAmount: bigint;
        claimedAmount: bigint;
      }
    ],
    "view"
  >;

  poolQualityGates: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, boolean, bigint] & {
        minQualityScore: bigint;
        requiresApproval: boolean;
        autoReleaseDelay: bigint;
      }
    ],
    "view"
  >;

  pools: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        poolId: string;
        owner: string;
        name: string;
        description: string;
        totalBudget: bigint;
        fundedAmount: bigint;
        reservedAmount: bigint;
        releasedAmount: bigint;
        token: string;
        status: bigint;
        createdAt: bigint;
        deadline: bigint;
      }
    ],
    "view"
  >;

  rejectMilestone: TypedContractMethod<
    [_milestoneId: BytesLike, _reason: string],
    [void],
    "nonpayable"
  >;

  releaseMilestoneFunds: TypedContractMethod<
    [_milestoneId: BytesLike],
    [void],
    "nonpayable"
  >;

  removeApprover: TypedContractMethod<
    [_poolId: BytesLike, _approver: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setOperator: TypedContractMethod<
    [_operator: AddressLike, _authorized: boolean],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  settlementToken: TypedContractMethod<[], [string], "view">;

  startMilestone: TypedContractMethod<
    [_milestoneId: BytesLike],
    [void],
    "nonpayable"
  >;

  submitMilestone: TypedContractMethod<
    [_milestoneId: BytesLike, _deliverableHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_MILESTONES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_POOL_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activatePool"
  ): TypedContractMethod<[_poolId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addApprover"
  ): TypedContractMethod<
    [_poolId: BytesLike, _approver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allPoolIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "approveMilestone"
  ): TypedContractMethod<
    [_milestoneId: BytesLike, _qualityScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMilestone"
  ): TypedContractMethod<
    [
      _poolId: BytesLike,
      _title: string,
      _description: string,
      _percentOfPool: BigNumberish,
      _participants: AddressLike[],
      _shares: BigNumberish[]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<
    [
      _name: string,
      _description: string,
      _totalBudget: BigNumberish,
      _deadline: BigNumberish,
      _qualityGate: BudgetPool.QualityGateStruct
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundPool"
  ): TypedContractMethod<
    [_poolId: BytesLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMilestone"
  ): TypedContractMethod<
    [_milestoneId: BytesLike],
    [BudgetPool.MilestoneStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnerPools"
  ): TypedContractMethod<[_owner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getParticipant"
  ): TypedContractMethod<
    [_poolId: BytesLike, _participant: AddressLike],
    [BudgetPool.ParticipantStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingBalance"
  ): TypedContractMethod<[_account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPool"
  ): TypedContractMethod<
    [_poolId: BytesLike],
    [BudgetPool.PoolStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolMilestones"
  ): TypedContractMethod<[_poolId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getQualityGate"
  ): TypedContractMethod<
    [_poolId: BytesLike],
    [BudgetPool.QualityGateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "milestones"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        milestoneId: string;
        poolId: string;
        title: string;
        description: string;
        budgetAmount: bigint;
        percentOfPool: bigint;
        status: bigint;
        deliverableHash: string;
        submittedAt: bigint;
        approvedAt: bigint;
        approver: string;
        qualityScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerPools"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolApprovers"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolMilestones"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolParticipants"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        wallet: string;
        totalEarned: bigint;
        pendingAmount: bigint;
        claimedAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolQualityGates"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, boolean, bigint] & {
        minQualityScore: bigint;
        requiresApproval: boolean;
        autoReleaseDelay: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        poolId: string;
        owner: string;
        name: string;
        description: string;
        totalBudget: bigint;
        fundedAmount: bigint;
        reservedAmount: bigint;
        releasedAmount: bigint;
        token: string;
        status: bigint;
        createdAt: bigint;
        deadline: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rejectMilestone"
  ): TypedContractMethod<
    [_milestoneId: BytesLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseMilestoneFunds"
  ): TypedContractMethod<[_milestoneId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeApprover"
  ): TypedContractMethod<
    [_poolId: BytesLike, _approver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [_operator: AddressLike, _authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlementToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "startMilestone"
  ): TypedContractMethod<[_milestoneId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitMilestone"
  ): TypedContractMethod<
    [_milestoneId: BytesLike, _deliverableHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneApproved"
  ): TypedContractEvent<
    MilestoneApprovedEvent.InputTuple,
    MilestoneApprovedEvent.OutputTuple,
    MilestoneApprovedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneCreated"
  ): TypedContractEvent<
    MilestoneCreatedEvent.InputTuple,
    MilestoneCreatedEvent.OutputTuple,
    MilestoneCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneRejected"
  ): TypedContractEvent<
    MilestoneRejectedEvent.InputTuple,
    MilestoneRejectedEvent.OutputTuple,
    MilestoneRejectedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneStatusChanged"
  ): TypedContractEvent<
    MilestoneStatusChangedEvent.InputTuple,
    MilestoneStatusChangedEvent.OutputTuple,
    MilestoneStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneSubmitted"
  ): TypedContractEvent<
    MilestoneSubmittedEvent.InputTuple,
    MilestoneSubmittedEvent.OutputTuple,
    MilestoneSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorUpdated"
  ): TypedContractEvent<
    OperatorUpdatedEvent.InputTuple,
    OperatorUpdatedEvent.OutputTuple,
    OperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantPaid"
  ): TypedContractEvent<
    ParticipantPaidEvent.InputTuple,
    ParticipantPaidEvent.OutputTuple,
    ParticipantPaidEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolFunded"
  ): TypedContractEvent<
    PoolFundedEvent.InputTuple,
    PoolFundedEvent.OutputTuple,
    PoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "PoolStatusChanged"
  ): TypedContractEvent<
    PoolStatusChangedEvent.InputTuple,
    PoolStatusChangedEvent.OutputTuple,
    PoolStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "FundsReleased(bytes32,uint256,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "MilestoneApproved(bytes32,address,uint8)": TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;
    MilestoneApproved: TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;

    "MilestoneCreated(bytes32,bytes32,string,uint256)": TypedContractEvent<
      MilestoneCreatedEvent.InputTuple,
      MilestoneCreatedEvent.OutputTuple,
      MilestoneCreatedEvent.OutputObject
    >;
    MilestoneCreated: TypedContractEvent<
      MilestoneCreatedEvent.InputTuple,
      MilestoneCreatedEvent.OutputTuple,
      MilestoneCreatedEvent.OutputObject
    >;

    "MilestoneRejected(bytes32,address,string)": TypedContractEvent<
      MilestoneRejectedEvent.InputTuple,
      MilestoneRejectedEvent.OutputTuple,
      MilestoneRejectedEvent.OutputObject
    >;
    MilestoneRejected: TypedContractEvent<
      MilestoneRejectedEvent.InputTuple,
      MilestoneRejectedEvent.OutputTuple,
      MilestoneRejectedEvent.OutputObject
    >;

    "MilestoneStatusChanged(bytes32,uint8,uint8)": TypedContractEvent<
      MilestoneStatusChangedEvent.InputTuple,
      MilestoneStatusChangedEvent.OutputTuple,
      MilestoneStatusChangedEvent.OutputObject
    >;
    MilestoneStatusChanged: TypedContractEvent<
      MilestoneStatusChangedEvent.InputTuple,
      MilestoneStatusChangedEvent.OutputTuple,
      MilestoneStatusChangedEvent.OutputObject
    >;

    "MilestoneSubmitted(bytes32,bytes32,address)": TypedContractEvent<
      MilestoneSubmittedEvent.InputTuple,
      MilestoneSubmittedEvent.OutputTuple,
      MilestoneSubmittedEvent.OutputObject
    >;
    MilestoneSubmitted: TypedContractEvent<
      MilestoneSubmittedEvent.InputTuple,
      MilestoneSubmittedEvent.OutputTuple,
      MilestoneSubmittedEvent.OutputObject
    >;

    "OperatorUpdated(address,bool)": TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;
    OperatorUpdated: TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ParticipantPaid(bytes32,address,uint256)": TypedContractEvent<
      ParticipantPaidEvent.InputTuple,
      ParticipantPaidEvent.OutputTuple,
      ParticipantPaidEvent.OutputObject
    >;
    ParticipantPaid: TypedContractEvent<
      ParticipantPaidEvent.InputTuple,
      ParticipantPaidEvent.OutputTuple,
      ParticipantPaidEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PoolCreated(bytes32,address,string,uint256,address)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;

    "PoolFunded(bytes32,address,uint256)": TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;
    PoolFunded: TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;

    "PoolStatusChanged(bytes32,uint8,uint8)": TypedContractEvent<
      PoolStatusChangedEvent.InputTuple,
      PoolStatusChangedEvent.OutputTuple,
      PoolStatusChangedEvent.OutputObject
    >;
    PoolStatusChanged: TypedContractEvent<
      PoolStatusChangedEvent.InputTuple,
      PoolStatusChangedEvent.OutputTuple,
      PoolStatusChangedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
