/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Commission {
  export type SplitConfigStruct = {
    merchantMPCWallet: AddressLike;
    merchantAmount: BigNumberish;
    referrer: AddressLike;
    referralFee: BigNumberish;
    executor: AddressLike;
    executionFee: BigNumberish;
    platformFee: BigNumberish;
    offRampFee: BigNumberish;
    executorHasWallet: boolean;
    settlementTime: BigNumberish;
    isDisputed: boolean;
    sessionId: BytesLike;
    proofHash: BytesLike;
    auditor: AddressLike;
    requiresProof: boolean;
    proofVerified: boolean;
  };

  export type SplitConfigStructOutput = [
    merchantMPCWallet: string,
    merchantAmount: bigint,
    referrer: string,
    referralFee: bigint,
    executor: string,
    executionFee: bigint,
    platformFee: bigint,
    offRampFee: bigint,
    executorHasWallet: boolean,
    settlementTime: bigint,
    isDisputed: boolean,
    sessionId: string,
    proofHash: string,
    auditor: string,
    requiresProof: boolean,
    proofVerified: boolean
  ] & {
    merchantMPCWallet: string;
    merchantAmount: bigint;
    referrer: string;
    referralFee: bigint;
    executor: string;
    executionFee: bigint;
    platformFee: bigint;
    offRampFee: bigint;
    executorHasWallet: boolean;
    settlementTime: bigint;
    isDisputed: boolean;
    sessionId: string;
    proofHash: string;
    auditor: string;
    requiresProof: boolean;
    proofVerified: boolean;
  };
}

export interface CommissionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "EXECUTOR_SHARE"
      | "PROMOTER_SHARE_OF_PLATFORM"
      | "REFERRER_SHARE"
      | "authorizedProviders"
      | "autoPaySplit"
      | "calculateV5Split"
      | "commissions"
      | "configureSettlementToken"
      | "createSettlement"
      | "distributeCommission"
      | "emergencyWithdrawETH"
      | "emergencyWithdrawToken"
      | "executeSettlement"
      | "getContractBalance"
      | "getPendingBalance"
      | "getProofStatus"
      | "getSplitConfig"
      | "initializeV5Rates"
      | "layerPlatformFees"
      | "layerPoolRates"
      | "orderSplitConfigs"
      | "orders"
      | "owner"
      | "pause"
      | "paused"
      | "paymindTreasury"
      | "pendingBalances"
      | "providerFiatToCryptoSplit"
      | "quickPaySplit"
      | "quickPaySplitFrom"
      | "recordCommission"
      | "recordCommissionLegacy"
      | "relayers"
      | "renounceOwnership"
      | "scannedFeeRates"
      | "scannedProductSplit"
      | "setAuthorizedProvider"
      | "setDisputeStatus"
      | "setLayerRates"
      | "setOrderDispute"
      | "setProofRequirement"
      | "setRelayer"
      | "setScannedFeeRate"
      | "setSplitConfig"
      | "setTrustedAuditor"
      | "setX402ChannelFeeRate"
      | "settlementToken"
      | "settlements"
      | "submitProof"
      | "submittedProofs"
      | "syncOrder"
      | "systemRebatePool"
      | "transferOwnership"
      | "trustedAuditors"
      | "unpause"
      | "updateSystemRebatePool"
      | "verifyProof"
      | "walletSplit"
      | "x402ChannelFeeRate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommissionDistributed"
      | "CommissionRecorded"
      | "OrderSynced"
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentAutoSplit"
      | "PaymentReceived"
      | "ProofRejected"
      | "ProofSubmitted"
      | "ProofVerified"
      | "ProviderAuthorized"
      | "ScannedProductPayment"
      | "SettlementCompleted"
      | "SettlementCreated"
      | "SplitConfigSet"
      | "TrustedAuditorUpdated"
      | "Unpaused"
      | "X402ChannelFeeRateUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROMOTER_SHARE_OF_PLATFORM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFERRER_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedProviders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "autoPaySplit",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateV5Split",
    values: [BigNumberish, BigNumberish, boolean, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "commissions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "configureSettlementToken",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createSettlement",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeCommission",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawETH",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSettlement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingBalance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProofStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSplitConfig",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV5Rates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "layerPlatformFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "layerPoolRates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "orderSplitConfigs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "orders", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymindTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingBalances",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "providerFiatToCryptoSplit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quickPaySplit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quickPaySplitFrom",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCommission",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCommissionLegacy",
    values: [AddressLike, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "relayers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scannedFeeRates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scannedProductSplit",
    values: [BytesLike, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedProvider",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDisputeStatus",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setLayerRates",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOrderDispute",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setProofRequirement",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setScannedFeeRate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSplitConfig",
    values: [BytesLike, Commission.SplitConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedAuditor",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setX402ChannelFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settlements",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submittedProofs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "syncOrder",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "systemRebatePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedAuditors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateSystemRebatePool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [BytesLike, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "walletSplit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "x402ChannelFeeRate",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROMOTER_SHARE_OF_PLATFORM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFERRER_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "autoPaySplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateV5Split",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureSettlementToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProofStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSplitConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeV5Rates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "layerPlatformFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "layerPoolRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "orderSplitConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymindTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerFiatToCryptoSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quickPaySplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quickPaySplitFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCommissionLegacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scannedFeeRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scannedProductSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDisputeStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLayerRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOrderDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProofRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setScannedFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSplitConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedAuditor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setX402ChannelFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submittedProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "syncOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "systemRebatePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedAuditors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateSystemRebatePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "walletSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "x402ChannelFeeRate",
    data: BytesLike
  ): Result;
}

export namespace CommissionDistributedEvent {
  export type InputTuple = [orderId: BytesLike, merchantAmount: BigNumberish];
  export type OutputTuple = [orderId: string, merchantAmount: bigint];
  export interface OutputObject {
    orderId: string;
    merchantAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommissionRecordedEvent {
  export type InputTuple = [
    recordId: BytesLike,
    payee: AddressLike,
    payeeType: BigNumberish,
    agentType: BigNumberish,
    amount: BigNumberish,
    currency: AddressLike,
    commissionBase: BigNumberish,
    channelFee: BigNumberish,
    sessionId: BytesLike
  ];
  export type OutputTuple = [
    recordId: string,
    payee: string,
    payeeType: bigint,
    agentType: bigint,
    amount: bigint,
    currency: string,
    commissionBase: bigint,
    channelFee: bigint,
    sessionId: string
  ];
  export interface OutputObject {
    recordId: string;
    payee: string;
    payeeType: bigint;
    agentType: bigint;
    amount: bigint;
    currency: string;
    commissionBase: bigint;
    channelFee: bigint;
    sessionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderSyncedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    status: BigNumberish,
    settlementTime: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    status: bigint,
    settlementTime: bigint
  ];
  export interface OutputObject {
    orderId: string;
    status: bigint;
    settlementTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentAutoSplitEvent {
  export type InputTuple = [
    orderId: BytesLike,
    sessionId: BytesLike,
    merchantWallet: AddressLike,
    totalAmount: BigNumberish,
    merchantAmount: BigNumberish,
    platformFee: BigNumberish,
    executionFee: BigNumberish,
    referralFee: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    sessionId: string,
    merchantWallet: string,
    totalAmount: bigint,
    merchantAmount: bigint,
    platformFee: bigint,
    executionFee: bigint,
    referralFee: bigint
  ];
  export interface OutputObject {
    orderId: string;
    sessionId: string;
    merchantWallet: string;
    totalAmount: bigint;
    merchantAmount: bigint;
    platformFee: bigint;
    executionFee: bigint;
    referralFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReceivedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    scenario: BigNumberish,
    from: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    scenario: bigint,
    from: string,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: string;
    scenario: bigint;
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofRejectedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    reason: string,
    auditor: AddressLike
  ];
  export type OutputTuple = [orderId: string, reason: string, auditor: string];
  export interface OutputObject {
    orderId: string;
    reason: string;
    auditor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    resultHash: BytesLike,
    submitter: AddressLike
  ];
  export type OutputTuple = [
    orderId: string,
    resultHash: string,
    submitter: string
  ];
  export interface OutputObject {
    orderId: string;
    resultHash: string;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofVerifiedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    resultHash: BytesLike,
    auditor: AddressLike,
    quality: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    resultHash: string,
    auditor: string,
    quality: bigint
  ];
  export interface OutputObject {
    orderId: string;
    resultHash: string;
    auditor: string;
    quality: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderAuthorizedEvent {
  export type InputTuple = [provider: AddressLike, authorized: boolean];
  export type OutputTuple = [provider: string, authorized: boolean];
  export interface OutputObject {
    provider: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScannedProductPaymentEvent {
  export type InputTuple = [
    orderId: BytesLike,
    source: BigNumberish,
    originalAmount: BigNumberish,
    userExtraFee: BigNumberish,
    merchantAmount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    source: bigint,
    originalAmount: bigint,
    userExtraFee: bigint,
    merchantAmount: bigint
  ];
  export interface OutputObject {
    orderId: string;
    source: bigint;
    originalAmount: bigint;
    userExtraFee: bigint;
    merchantAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementCompletedEvent {
  export type InputTuple = [
    settlementId: BytesLike,
    payee: AddressLike,
    amount: BigNumberish,
    currency: AddressLike
  ];
  export type OutputTuple = [
    settlementId: string,
    payee: string,
    amount: bigint,
    currency: string
  ];
  export interface OutputObject {
    settlementId: string;
    payee: string;
    amount: bigint;
    currency: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementCreatedEvent {
  export type InputTuple = [
    settlementId: BytesLike,
    payee: AddressLike,
    payeeType: BigNumberish,
    totalAmount: BigNumberish,
    currency: AddressLike
  ];
  export type OutputTuple = [
    settlementId: string,
    payee: string,
    payeeType: bigint,
    totalAmount: bigint,
    currency: string
  ];
  export interface OutputObject {
    settlementId: string;
    payee: string;
    payeeType: bigint;
    totalAmount: bigint;
    currency: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitConfigSetEvent {
  export type InputTuple = [
    orderId: BytesLike,
    config: Commission.SplitConfigStruct
  ];
  export type OutputTuple = [
    orderId: string,
    config: Commission.SplitConfigStructOutput
  ];
  export interface OutputObject {
    orderId: string;
    config: Commission.SplitConfigStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedAuditorUpdatedEvent {
  export type InputTuple = [auditor: AddressLike, trusted: boolean];
  export type OutputTuple = [auditor: string, trusted: boolean];
  export interface OutputObject {
    auditor: string;
    trusted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace X402ChannelFeeRateUpdatedEvent {
  export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
  export type OutputTuple = [oldRate: bigint, newRate: bigint];
  export interface OutputObject {
    oldRate: bigint;
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Commission extends BaseContract {
  connect(runner?: ContractRunner | null): Commission;
  waitForDeployment(): Promise<this>;

  interface: CommissionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  EXECUTOR_SHARE: TypedContractMethod<[], [bigint], "view">;

  PROMOTER_SHARE_OF_PLATFORM: TypedContractMethod<[], [bigint], "view">;

  REFERRER_SHARE: TypedContractMethod<[], [bigint], "view">;

  authorizedProviders: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  autoPaySplit: TypedContractMethod<
    [orderId: BytesLike, amount: BigNumberish, payer: AddressLike],
    [void],
    "nonpayable"
  >;

  calculateV5Split: TypedContractMethod<
    [
      amount: BigNumberish,
      layer: BigNumberish,
      hasReferrer: boolean,
      hasExecutor: boolean,
      executorHasWallet: boolean
    ],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        merchantAmount: bigint;
        platformFee: bigint;
        referrerFee: bigint;
        executorFee: bigint;
        treasuryFee: bigint;
      }
    ],
    "view"
  >;

  commissions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint,
        boolean
      ] & {
        recordId: string;
        payee: string;
        payeeType: bigint;
        agentType: bigint;
        amount: bigint;
        currency: string;
        commissionBase: bigint;
        channelFee: bigint;
        sessionId: string;
        timestamp: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;

  configureSettlementToken: TypedContractMethod<
    [token: AddressLike, treasury: AddressLike, rebatePool: AddressLike],
    [void],
    "nonpayable"
  >;

  createSettlement: TypedContractMethod<
    [payee: AddressLike, payeeType: BigNumberish, currency: AddressLike],
    [string],
    "nonpayable"
  >;

  distributeCommission: TypedContractMethod<
    [orderId: BytesLike],
    [void],
    "nonpayable"
  >;

  emergencyWithdrawETH: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdrawToken: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeSettlement: TypedContractMethod<
    [settlementId: BytesLike],
    [void],
    "nonpayable"
  >;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getPendingBalance: TypedContractMethod<
    [payee: AddressLike, currency: AddressLike],
    [bigint],
    "view"
  >;

  getProofStatus: TypedContractMethod<
    [orderId: BytesLike],
    [
      [boolean, string, string, boolean, string] & {
        requiresProof: boolean;
        expectedHash: string;
        submittedHash: string;
        verified: boolean;
        auditor: string;
      }
    ],
    "view"
  >;

  getSplitConfig: TypedContractMethod<
    [orderId: BytesLike],
    [Commission.SplitConfigStructOutput],
    "view"
  >;

  initializeV5Rates: TypedContractMethod<[], [void], "nonpayable">;

  layerPlatformFees: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  layerPoolRates: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  orderSplitConfigs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean,
        string,
        string,
        string,
        boolean,
        boolean
      ] & {
        merchantMPCWallet: string;
        merchantAmount: bigint;
        referrer: string;
        referralFee: bigint;
        executor: string;
        executionFee: bigint;
        platformFee: bigint;
        offRampFee: bigint;
        executorHasWallet: boolean;
        settlementTime: bigint;
        isDisputed: boolean;
        sessionId: string;
        proofHash: string;
        auditor: string;
        requiresProof: boolean;
        proofVerified: boolean;
      }
    ],
    "view"
  >;

  orders: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        orderId: string;
        merchant: string;
        referrer: string;
        executor: string;
        merchantAmount: bigint;
        referralFee: bigint;
        executionFee: bigint;
        platformFee: bigint;
        settlementTime: bigint;
        executorHasWallet: boolean;
        isDisputed: boolean;
        status: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymindTreasury: TypedContractMethod<[], [string], "view">;

  pendingBalances: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  providerFiatToCryptoSplit: TypedContractMethod<
    [orderId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  quickPaySplit: TypedContractMethod<
    [orderId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  quickPaySplitFrom: TypedContractMethod<
    [orderId: BytesLike, amount: BigNumberish, payer: AddressLike],
    [void],
    "nonpayable"
  >;

  recordCommission: TypedContractMethod<
    [
      payee: AddressLike,
      payeeType: BigNumberish,
      agentType: BigNumberish,
      amount: BigNumberish,
      currency: AddressLike,
      commissionBase: BigNumberish,
      channelFee: BigNumberish,
      sessionId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  recordCommissionLegacy: TypedContractMethod<
    [
      payee: AddressLike,
      payeeType: BigNumberish,
      amount: BigNumberish,
      currency: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  relayers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scannedFeeRates: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  scannedProductSplit: TypedContractMethod<
    [
      orderId: BytesLike,
      originalAmount: BigNumberish,
      source: BigNumberish,
      referrer: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setAuthorizedProvider: TypedContractMethod<
    [provider: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  setDisputeStatus: TypedContractMethod<
    [orderId: BytesLike, isDisputed: boolean],
    [void],
    "nonpayable"
  >;

  setLayerRates: TypedContractMethod<
    [layer: BigNumberish, platformFee: BigNumberish, poolRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setOrderDispute: TypedContractMethod<
    [orderId: BytesLike, disputed: boolean],
    [void],
    "nonpayable"
  >;

  setProofRequirement: TypedContractMethod<
    [orderId: BytesLike, proofHash: BytesLike, auditor: AddressLike],
    [void],
    "nonpayable"
  >;

  setRelayer: TypedContractMethod<
    [relayer: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;

  setScannedFeeRate: TypedContractMethod<
    [source: BigNumberish, rate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSplitConfig: TypedContractMethod<
    [orderId: BytesLike, config: Commission.SplitConfigStruct],
    [void],
    "nonpayable"
  >;

  setTrustedAuditor: TypedContractMethod<
    [auditor: AddressLike, trusted: boolean],
    [void],
    "nonpayable"
  >;

  setX402ChannelFeeRate: TypedContractMethod<
    [newRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  settlementToken: TypedContractMethod<[], [string], "view">;

  settlements: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string, bigint, boolean] & {
        settlementId: string;
        payee: string;
        payeeType: bigint;
        totalAmount: bigint;
        currency: string;
        settlementDate: bigint;
        completed: boolean;
      }
    ],
    "view"
  >;

  submitProof: TypedContractMethod<
    [orderId: BytesLike, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;

  submittedProofs: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  syncOrder: TypedContractMethod<
    [
      orderId: BytesLike,
      merchant: AddressLike,
      referrer: AddressLike,
      executor: AddressLike,
      merchantAmount: BigNumberish,
      referralFee: BigNumberish,
      executionFee: BigNumberish,
      platformFee: BigNumberish,
      settlementTime: BigNumberish,
      executorHasWallet: boolean,
      isDisputed: boolean,
      status: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  systemRebatePool: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedAuditors: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateSystemRebatePool: TypedContractMethod<
    [rebatePool: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyProof: TypedContractMethod<
    [orderId: BytesLike, approved: boolean, quality: BigNumberish],
    [void],
    "nonpayable"
  >;

  walletSplit: TypedContractMethod<
    [orderId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  x402ChannelFeeRate: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EXECUTOR_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROMOTER_SHARE_OF_PLATFORM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFERRER_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizedProviders"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "autoPaySplit"
  ): TypedContractMethod<
    [orderId: BytesLike, amount: BigNumberish, payer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateV5Split"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      layer: BigNumberish,
      hasReferrer: boolean,
      hasExecutor: boolean,
      executorHasWallet: boolean
    ],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        merchantAmount: bigint;
        platformFee: bigint;
        referrerFee: bigint;
        executorFee: bigint;
        treasuryFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "commissions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        bigint,
        boolean
      ] & {
        recordId: string;
        payee: string;
        payeeType: bigint;
        agentType: bigint;
        amount: bigint;
        currency: string;
        commissionBase: bigint;
        channelFee: bigint;
        sessionId: string;
        timestamp: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "configureSettlementToken"
  ): TypedContractMethod<
    [token: AddressLike, treasury: AddressLike, rebatePool: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSettlement"
  ): TypedContractMethod<
    [payee: AddressLike, payeeType: BigNumberish, currency: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeCommission"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdrawETH"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdrawToken"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeSettlement"
  ): TypedContractMethod<[settlementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingBalance"
  ): TypedContractMethod<
    [payee: AddressLike, currency: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProofStatus"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [
      [boolean, string, string, boolean, string] & {
        requiresProof: boolean;
        expectedHash: string;
        submittedHash: string;
        verified: boolean;
        auditor: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSplitConfig"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [Commission.SplitConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initializeV5Rates"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "layerPlatformFees"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "layerPoolRates"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "orderSplitConfigs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean,
        string,
        string,
        string,
        boolean,
        boolean
      ] & {
        merchantMPCWallet: string;
        merchantAmount: bigint;
        referrer: string;
        referralFee: bigint;
        executor: string;
        executionFee: bigint;
        platformFee: bigint;
        offRampFee: bigint;
        executorHasWallet: boolean;
        settlementTime: bigint;
        isDisputed: boolean;
        sessionId: string;
        proofHash: string;
        auditor: string;
        requiresProof: boolean;
        proofVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        orderId: string;
        merchant: string;
        referrer: string;
        executor: string;
        merchantAmount: bigint;
        referralFee: bigint;
        executionFee: bigint;
        platformFee: bigint;
        settlementTime: bigint;
        executorHasWallet: boolean;
        isDisputed: boolean;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymindTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingBalances"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "providerFiatToCryptoSplit"
  ): TypedContractMethod<
    [orderId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "quickPaySplit"
  ): TypedContractMethod<
    [orderId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "quickPaySplitFrom"
  ): TypedContractMethod<
    [orderId: BytesLike, amount: BigNumberish, payer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordCommission"
  ): TypedContractMethod<
    [
      payee: AddressLike,
      payeeType: BigNumberish,
      agentType: BigNumberish,
      amount: BigNumberish,
      currency: AddressLike,
      commissionBase: BigNumberish,
      channelFee: BigNumberish,
      sessionId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordCommissionLegacy"
  ): TypedContractMethod<
    [
      payee: AddressLike,
      payeeType: BigNumberish,
      amount: BigNumberish,
      currency: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "relayers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scannedFeeRates"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "scannedProductSplit"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      originalAmount: BigNumberish,
      source: BigNumberish,
      referrer: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedProvider"
  ): TypedContractMethod<
    [provider: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDisputeStatus"
  ): TypedContractMethod<
    [orderId: BytesLike, isDisputed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLayerRates"
  ): TypedContractMethod<
    [layer: BigNumberish, platformFee: BigNumberish, poolRate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOrderDispute"
  ): TypedContractMethod<
    [orderId: BytesLike, disputed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProofRequirement"
  ): TypedContractMethod<
    [orderId: BytesLike, proofHash: BytesLike, auditor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRelayer"
  ): TypedContractMethod<
    [relayer: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setScannedFeeRate"
  ): TypedContractMethod<
    [source: BigNumberish, rate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSplitConfig"
  ): TypedContractMethod<
    [orderId: BytesLike, config: Commission.SplitConfigStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTrustedAuditor"
  ): TypedContractMethod<
    [auditor: AddressLike, trusted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setX402ChannelFeeRate"
  ): TypedContractMethod<[newRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlementToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "settlements"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string, bigint, boolean] & {
        settlementId: string;
        payee: string;
        payeeType: bigint;
        totalAmount: bigint;
        currency: string;
        settlementDate: bigint;
        completed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [orderId: BytesLike, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submittedProofs"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "syncOrder"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      merchant: AddressLike,
      referrer: AddressLike,
      executor: AddressLike,
      merchantAmount: BigNumberish,
      referralFee: BigNumberish,
      executionFee: BigNumberish,
      platformFee: BigNumberish,
      settlementTime: BigNumberish,
      executorHasWallet: boolean,
      isDisputed: boolean,
      status: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "systemRebatePool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedAuditors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSystemRebatePool"
  ): TypedContractMethod<[rebatePool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<
    [orderId: BytesLike, approved: boolean, quality: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "walletSplit"
  ): TypedContractMethod<
    [orderId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "x402ChannelFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "CommissionDistributed"
  ): TypedContractEvent<
    CommissionDistributedEvent.InputTuple,
    CommissionDistributedEvent.OutputTuple,
    CommissionDistributedEvent.OutputObject
  >;
  getEvent(
    key: "CommissionRecorded"
  ): TypedContractEvent<
    CommissionRecordedEvent.InputTuple,
    CommissionRecordedEvent.OutputTuple,
    CommissionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OrderSynced"
  ): TypedContractEvent<
    OrderSyncedEvent.InputTuple,
    OrderSyncedEvent.OutputTuple,
    OrderSyncedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentAutoSplit"
  ): TypedContractEvent<
    PaymentAutoSplitEvent.InputTuple,
    PaymentAutoSplitEvent.OutputTuple,
    PaymentAutoSplitEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReceived"
  ): TypedContractEvent<
    PaymentReceivedEvent.InputTuple,
    PaymentReceivedEvent.OutputTuple,
    PaymentReceivedEvent.OutputObject
  >;
  getEvent(
    key: "ProofRejected"
  ): TypedContractEvent<
    ProofRejectedEvent.InputTuple,
    ProofRejectedEvent.OutputTuple,
    ProofRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ProofVerified"
  ): TypedContractEvent<
    ProofVerifiedEvent.InputTuple,
    ProofVerifiedEvent.OutputTuple,
    ProofVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "ProviderAuthorized"
  ): TypedContractEvent<
    ProviderAuthorizedEvent.InputTuple,
    ProviderAuthorizedEvent.OutputTuple,
    ProviderAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "ScannedProductPayment"
  ): TypedContractEvent<
    ScannedProductPaymentEvent.InputTuple,
    ScannedProductPaymentEvent.OutputTuple,
    ScannedProductPaymentEvent.OutputObject
  >;
  getEvent(
    key: "SettlementCompleted"
  ): TypedContractEvent<
    SettlementCompletedEvent.InputTuple,
    SettlementCompletedEvent.OutputTuple,
    SettlementCompletedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementCreated"
  ): TypedContractEvent<
    SettlementCreatedEvent.InputTuple,
    SettlementCreatedEvent.OutputTuple,
    SettlementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SplitConfigSet"
  ): TypedContractEvent<
    SplitConfigSetEvent.InputTuple,
    SplitConfigSetEvent.OutputTuple,
    SplitConfigSetEvent.OutputObject
  >;
  getEvent(
    key: "TrustedAuditorUpdated"
  ): TypedContractEvent<
    TrustedAuditorUpdatedEvent.InputTuple,
    TrustedAuditorUpdatedEvent.OutputTuple,
    TrustedAuditorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "X402ChannelFeeRateUpdated"
  ): TypedContractEvent<
    X402ChannelFeeRateUpdatedEvent.InputTuple,
    X402ChannelFeeRateUpdatedEvent.OutputTuple,
    X402ChannelFeeRateUpdatedEvent.OutputObject
  >;

  filters: {
    "CommissionDistributed(bytes32,uint256)": TypedContractEvent<
      CommissionDistributedEvent.InputTuple,
      CommissionDistributedEvent.OutputTuple,
      CommissionDistributedEvent.OutputObject
    >;
    CommissionDistributed: TypedContractEvent<
      CommissionDistributedEvent.InputTuple,
      CommissionDistributedEvent.OutputTuple,
      CommissionDistributedEvent.OutputObject
    >;

    "CommissionRecorded(bytes32,address,uint8,uint8,uint256,address,uint256,uint256,bytes32)": TypedContractEvent<
      CommissionRecordedEvent.InputTuple,
      CommissionRecordedEvent.OutputTuple,
      CommissionRecordedEvent.OutputObject
    >;
    CommissionRecorded: TypedContractEvent<
      CommissionRecordedEvent.InputTuple,
      CommissionRecordedEvent.OutputTuple,
      CommissionRecordedEvent.OutputObject
    >;

    "OrderSynced(bytes32,uint8,uint256)": TypedContractEvent<
      OrderSyncedEvent.InputTuple,
      OrderSyncedEvent.OutputTuple,
      OrderSyncedEvent.OutputObject
    >;
    OrderSynced: TypedContractEvent<
      OrderSyncedEvent.InputTuple,
      OrderSyncedEvent.OutputTuple,
      OrderSyncedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentAutoSplit(bytes32,bytes32,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      PaymentAutoSplitEvent.InputTuple,
      PaymentAutoSplitEvent.OutputTuple,
      PaymentAutoSplitEvent.OutputObject
    >;
    PaymentAutoSplit: TypedContractEvent<
      PaymentAutoSplitEvent.InputTuple,
      PaymentAutoSplitEvent.OutputTuple,
      PaymentAutoSplitEvent.OutputObject
    >;

    "PaymentReceived(bytes32,uint8,address,uint256)": TypedContractEvent<
      PaymentReceivedEvent.InputTuple,
      PaymentReceivedEvent.OutputTuple,
      PaymentReceivedEvent.OutputObject
    >;
    PaymentReceived: TypedContractEvent<
      PaymentReceivedEvent.InputTuple,
      PaymentReceivedEvent.OutputTuple,
      PaymentReceivedEvent.OutputObject
    >;

    "ProofRejected(bytes32,string,address)": TypedContractEvent<
      ProofRejectedEvent.InputTuple,
      ProofRejectedEvent.OutputTuple,
      ProofRejectedEvent.OutputObject
    >;
    ProofRejected: TypedContractEvent<
      ProofRejectedEvent.InputTuple,
      ProofRejectedEvent.OutputTuple,
      ProofRejectedEvent.OutputObject
    >;

    "ProofSubmitted(bytes32,bytes32,address)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "ProofVerified(bytes32,bytes32,address,uint256)": TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;
    ProofVerified: TypedContractEvent<
      ProofVerifiedEvent.InputTuple,
      ProofVerifiedEvent.OutputTuple,
      ProofVerifiedEvent.OutputObject
    >;

    "ProviderAuthorized(address,bool)": TypedContractEvent<
      ProviderAuthorizedEvent.InputTuple,
      ProviderAuthorizedEvent.OutputTuple,
      ProviderAuthorizedEvent.OutputObject
    >;
    ProviderAuthorized: TypedContractEvent<
      ProviderAuthorizedEvent.InputTuple,
      ProviderAuthorizedEvent.OutputTuple,
      ProviderAuthorizedEvent.OutputObject
    >;

    "ScannedProductPayment(bytes32,uint8,uint256,uint256,uint256)": TypedContractEvent<
      ScannedProductPaymentEvent.InputTuple,
      ScannedProductPaymentEvent.OutputTuple,
      ScannedProductPaymentEvent.OutputObject
    >;
    ScannedProductPayment: TypedContractEvent<
      ScannedProductPaymentEvent.InputTuple,
      ScannedProductPaymentEvent.OutputTuple,
      ScannedProductPaymentEvent.OutputObject
    >;

    "SettlementCompleted(bytes32,address,uint256,address)": TypedContractEvent<
      SettlementCompletedEvent.InputTuple,
      SettlementCompletedEvent.OutputTuple,
      SettlementCompletedEvent.OutputObject
    >;
    SettlementCompleted: TypedContractEvent<
      SettlementCompletedEvent.InputTuple,
      SettlementCompletedEvent.OutputTuple,
      SettlementCompletedEvent.OutputObject
    >;

    "SettlementCreated(bytes32,address,uint8,uint256,address)": TypedContractEvent<
      SettlementCreatedEvent.InputTuple,
      SettlementCreatedEvent.OutputTuple,
      SettlementCreatedEvent.OutputObject
    >;
    SettlementCreated: TypedContractEvent<
      SettlementCreatedEvent.InputTuple,
      SettlementCreatedEvent.OutputTuple,
      SettlementCreatedEvent.OutputObject
    >;

    "SplitConfigSet(bytes32,tuple)": TypedContractEvent<
      SplitConfigSetEvent.InputTuple,
      SplitConfigSetEvent.OutputTuple,
      SplitConfigSetEvent.OutputObject
    >;
    SplitConfigSet: TypedContractEvent<
      SplitConfigSetEvent.InputTuple,
      SplitConfigSetEvent.OutputTuple,
      SplitConfigSetEvent.OutputObject
    >;

    "TrustedAuditorUpdated(address,bool)": TypedContractEvent<
      TrustedAuditorUpdatedEvent.InputTuple,
      TrustedAuditorUpdatedEvent.OutputTuple,
      TrustedAuditorUpdatedEvent.OutputObject
    >;
    TrustedAuditorUpdated: TypedContractEvent<
      TrustedAuditorUpdatedEvent.InputTuple,
      TrustedAuditorUpdatedEvent.OutputTuple,
      TrustedAuditorUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "X402ChannelFeeRateUpdated(uint16,uint16)": TypedContractEvent<
      X402ChannelFeeRateUpdatedEvent.InputTuple,
      X402ChannelFeeRateUpdatedEvent.OutputTuple,
      X402ChannelFeeRateUpdatedEvent.OutputObject
    >;
    X402ChannelFeeRateUpdated: TypedContractEvent<
      X402ChannelFeeRateUpdatedEvent.InputTuple,
      X402ChannelFeeRateUpdatedEvent.OutputTuple,
      X402ChannelFeeRateUpdatedEvent.OutputObject
    >;
  };
}
