/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PaymentRouter {
  export type PaymentRecordStruct = {
    paymentId: BytesLike;
    payer: AddressLike;
    recipient: AddressLike;
    amount: BigNumberish;
    method: BigNumberish;
    sessionId: BytesLike;
    merchantPrice: BigNumberish;
    channelFee: BigNumberish;
    completed: boolean;
    timestamp: BigNumberish;
  };

  export type PaymentRecordStructOutput = [
    paymentId: string,
    payer: string,
    recipient: string,
    amount: bigint,
    method: bigint,
    sessionId: string,
    merchantPrice: bigint,
    channelFee: bigint,
    completed: boolean,
    timestamp: bigint
  ] & {
    paymentId: string;
    payer: string;
    recipient: string;
    amount: bigint;
    method: bigint;
    sessionId: string;
    merchantPrice: bigint;
    channelFee: bigint;
    completed: boolean;
    timestamp: bigint;
  };
}

export interface PaymentRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balances"
      | "completePayment"
      | "emergencyWithdraw"
      | "getPayment"
      | "owner"
      | "pause"
      | "paused"
      | "paymentChannels"
      | "payments"
      | "renounceOwnership"
      | "routePayment"
      | "routePaymentLegacy"
      | "setPaymentChannel"
      | "transferOwnership"
      | "unpause"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentCompleted"
      | "PaymentRouted"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completePayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentChannels",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "payments", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "routePayment",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "routePaymentLegacy",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentChannel",
    values: [
      BigNumberish,
      AddressLike,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentChannels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "routePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "routePaymentLegacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCompletedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRoutedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    payer: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    method: BigNumberish,
    sessionId: BytesLike,
    merchantPrice: BigNumberish,
    channelFee: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    payer: string,
    recipient: string,
    amount: bigint,
    method: bigint,
    sessionId: string,
    merchantPrice: bigint,
    channelFee: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    payer: string;
    recipient: string;
    amount: bigint;
    method: bigint;
    sessionId: string;
    merchantPrice: bigint;
    channelFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentRouter extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentRouter;
  waitForDeployment(): Promise<this>;

  interface: PaymentRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  completePayment: TypedContractMethod<
    [paymentId: BytesLike],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPayment: TypedContractMethod<
    [paymentId: BytesLike],
    [PaymentRouter.PaymentRecordStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymentChannels: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, boolean, bigint, bigint, bigint] & {
        channelAddress: string;
        isActive: boolean;
        priority: bigint;
        minAmount: bigint;
        maxAmount: bigint;
      }
    ],
    "view"
  >;

  payments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        paymentId: string;
        payer: string;
        recipient: string;
        amount: bigint;
        method: bigint;
        sessionId: string;
        merchantPrice: bigint;
        channelFee: bigint;
        completed: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  routePayment: TypedContractMethod<
    [
      paymentId: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      method: BigNumberish,
      sessionId: BytesLike,
      merchantPrice: BigNumberish,
      channelFee: BigNumberish
    ],
    [void],
    "payable"
  >;

  routePaymentLegacy: TypedContractMethod<
    [
      paymentId: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      method: BigNumberish
    ],
    [void],
    "payable"
  >;

  setPaymentChannel: TypedContractMethod<
    [
      method: BigNumberish,
      channelAddress: AddressLike,
      isActive: boolean,
      priority: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "completePayment"
  ): TypedContractMethod<[paymentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [PaymentRouter.PaymentRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentChannels"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, boolean, bigint, bigint, bigint] & {
        channelAddress: string;
        isActive: boolean;
        priority: bigint;
        minAmount: bigint;
        maxAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        paymentId: string;
        payer: string;
        recipient: string;
        amount: bigint;
        method: bigint;
        sessionId: string;
        merchantPrice: bigint;
        channelFee: bigint;
        completed: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "routePayment"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      method: BigNumberish,
      sessionId: BytesLike,
      merchantPrice: BigNumberish,
      channelFee: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "routePaymentLegacy"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      method: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setPaymentChannel"
  ): TypedContractMethod<
    [
      method: BigNumberish,
      channelAddress: AddressLike,
      isActive: boolean,
      priority: BigNumberish,
      minAmount: BigNumberish,
      maxAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCompleted"
  ): TypedContractEvent<
    PaymentCompletedEvent.InputTuple,
    PaymentCompletedEvent.OutputTuple,
    PaymentCompletedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRouted"
  ): TypedContractEvent<
    PaymentRoutedEvent.InputTuple,
    PaymentRoutedEvent.OutputTuple,
    PaymentRoutedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentCompleted(bytes32,address,uint256)": TypedContractEvent<
      PaymentCompletedEvent.InputTuple,
      PaymentCompletedEvent.OutputTuple,
      PaymentCompletedEvent.OutputObject
    >;
    PaymentCompleted: TypedContractEvent<
      PaymentCompletedEvent.InputTuple,
      PaymentCompletedEvent.OutputTuple,
      PaymentCompletedEvent.OutputObject
    >;

    "PaymentRouted(bytes32,address,address,uint256,uint8,bytes32,uint256,uint256)": TypedContractEvent<
      PaymentRoutedEvent.InputTuple,
      PaymentRoutedEvent.OutputTuple,
      PaymentRoutedEvent.OutputObject
    >;
    PaymentRouted: TypedContractEvent<
      PaymentRoutedEvent.InputTuple,
      PaymentRoutedEvent.OutputTuple,
      PaymentRoutedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
