#Requires -Version 5.1
# ============================================================
# Agentrix OpenClaw Standard Installer (Windows PowerShell)
# Lightweight: installs the OpenClaw agent only.
# Prerequisites: Node.js >=18 must already be installed.
# For fully automatic setup (Node.js bundled), use:
#   irm https://cdn.agentrix.io/install-aio.ps1 | iex
# ============================================================
param(
  [int]$Port = 7474,
  [switch]$NoStart
)

$ErrorActionPreference = 'Stop'
$AGENTRIX_VERSION = '1.1.0'
$INSTALL_DIR = Join-Path $env:APPDATA 'Agentrix'
$LOG_FILE    = Join-Path $INSTALL_DIR 'install.log'

New-Item -ItemType Directory -Force -Path $INSTALL_DIR | Out-Null
Start-Transcript -Path $LOG_FILE -Append | Out-Null

function cinfo { param($msg) Write-Host "[Agentrix] $msg" -ForegroundColor Cyan }
function cok   { param($msg) Write-Host "[OK] $msg" -ForegroundColor Green }
function cwarn { param($msg) Write-Host "[!]  $msg" -ForegroundColor Yellow }
function cerr  { param($msg) Write-Host "[ERR] $msg" -ForegroundColor Red; exit 1 }

cinfo "Agentrix OpenClaw Standard Installer v$AGENTRIX_VERSION"
cinfo "Install directory: $INSTALL_DIR"

# ── 1. Check Node.js >=18 ───────────────────────────────────────────────────
try {
  $nodever = node -e "process.stdout.write(process.versions.node)" 2>$null
  $major   = [int]($nodever.Split('.')[0])
  if ($major -lt 18) {
    cerr "Node.js $nodever found but >=18 required. Upgrade from https://nodejs.org"
  }
  cok "Node.js $nodever"
} catch {
  cerr "Node.js not found. Install from https://nodejs.org (>=18) then re-run."
}

# ── 2. Install OpenClaw via npm ─────────────────────────────────────────────
cinfo "Installing @agentrix/openclaw-agent..."
try {
  npm install -g "@agentrix/openclaw-agent@latest" 2>$null
  cok "Installed @agentrix/openclaw-agent"
} catch {
  cwarn "npm install failed. Downloading binary from CDN..."
  $OC_DIR = Join-Path $INSTALL_DIR 'openclaw'
  New-Item -ItemType Directory -Force $OC_DIR | Out-Null

  $ARCH = if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') { 'arm64' } else { 'x64' }
  $BIN_URL = "https://cdn.agentrix.io/openclaw/latest/openclaw-windows-$ARCH.exe"
  $BIN_PATH = Join-Path $OC_DIR 'openclaw.exe'

  try {
    Invoke-WebRequest -Uri $BIN_URL -OutFile $BIN_PATH -UseBasicParsing
    cok "Binary downloaded to $BIN_PATH"
    # Add to PATH for this session
    $env:PATH = "$OC_DIR;$env:PATH"
  } catch {
    cerr "Could not download binary from $BIN_URL. Check Internet connection."
  }
}

# ── 3. Generate credentials ─────────────────────────────────────────────────
$randHex = { [System.BitConverter]::ToString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(24)).Replace('-','').ToLower() }
$INSTANCE_ID = "local-" + (node -e "process.stdout.write(Math.random().toString(36).slice(2,10))" 2>$null)
$RELAY_TOKEN  = (& $randHex)
$CONFIG = @{
  instanceId  = $INSTANCE_ID
  relayToken  = $RELAY_TOKEN
  port        = $Port
  version     = $AGENTRIX_VERSION
  deployType  = 'local'
  installedAt = (Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')
} | ConvertTo-Json -Depth 5
$CONFIG | Set-Content -Path (Join-Path $INSTALL_DIR 'config.json') -Encoding UTF8
cok "Config written to $INSTALL_DIR\config.json"

# ── 4. Create start/stop scripts ────────────────────────────────────────────
$START_PS1 = Join-Path $INSTALL_DIR 'Start-OpenClaw.ps1'
@"
# Auto-generated by Agentrix Standard Installer
openclaw start --port $Port --token $RELAY_TOKEN `$args
"@ | Set-Content $START_PS1 -Encoding UTF8

$STOP_PS1 = Join-Path $INSTALL_DIR 'Stop-OpenClaw.ps1'
@"
# Auto-generated by Agentrix Standard Installer
openclaw stop 2>`$null
if (-not `$?) { Stop-Process -Name 'openclaw' -Force -ErrorAction SilentlyContinue }
"@ | Set-Content $STOP_PS1 -Encoding UTF8

cok "Start/Stop scripts created in $INSTALL_DIR"

# ── 5. Print connection info ─────────────────────────────────────────────────
Write-Host ""
Write-Host "┌─────────────────────────────────────────────────┐" -ForegroundColor Cyan
Write-Host "│         Agentrix Standard - Ready               │" -ForegroundColor Cyan
Write-Host "├─────────────────────────────────────────────────┤" -ForegroundColor Cyan
Write-Host ("│  Instance ID : {0,-33}│" -f $INSTANCE_ID)
Write-Host ("│  Port        : {0,-33}│" -f $Port)
Write-Host ("│  Token       : {0,-33}│" -f ($RELAY_TOKEN.Substring(0,20) + "..."))
Write-Host "│                                                 │"
Write-Host "│  Start: Start-OpenClaw.ps1 in %APPDATA%\Agentrix│"
Write-Host "│  Mobile: Agent tab → + New Instance → Manual   │"
Write-Host "└─────────────────────────────────────────────────┘" -ForegroundColor Cyan

$DEEP_LINK = "agentrix://connect?instanceId=$INSTANCE_ID&token=$RELAY_TOKEN&port=$Port&host=localhost"
Write-Host "`n  Deep link (paste in mobile app):"
Write-Host "  $DEEP_LINK" -ForegroundColor Yellow

# ── 6. Start agent ───────────────────────────────────────────────────────────
if (-not $NoStart) {
  cinfo "Starting OpenClaw agent on port $Port..."
  Start-Process -FilePath 'powershell.exe' -ArgumentList "-File `"$START_PS1`"" -WindowStyle Minimized
  Start-Sleep -Seconds 3
  try {
    $health = Invoke-WebRequest -Uri "http://localhost:$Port/health" -UseBasicParsing -TimeoutSec 5
    if ($health.StatusCode -eq 200) { cok "Agent is running at http://localhost:$Port" }
  } catch {
    cwarn "Agent may still be starting. Try: curl http://localhost:$Port/health"
  }
}

Write-Host ""
cok "Standard installation complete!"
cinfo "Run: powershell -File `"$START_PS1`" to start, or add to Task Scheduler."
