/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAgentPayment {
  export type PaymentIntentStruct = {
    intentId: BytesLike;
    payer: AddressLike;
    recipients: AddressLike[];
    amounts: BigNumberish[];
    collaborationId: BytesLike;
    totalAmount: BigNumberish;
    createdAt: BigNumberish;
    expiresAt: BigNumberish;
    status: BigNumberish;
  };

  export type PaymentIntentStructOutput = [
    intentId: string,
    payer: string,
    recipients: string[],
    amounts: bigint[],
    collaborationId: string,
    totalAmount: bigint,
    createdAt: bigint,
    expiresAt: bigint,
    status: bigint
  ] & {
    intentId: string;
    payer: string;
    recipients: string[];
    amounts: bigint[];
    collaborationId: string;
    totalAmount: bigint;
    createdAt: bigint;
    expiresAt: bigint;
    status: bigint;
  };

  export type SplitConfigStruct = {
    merchantWallet: AddressLike;
    merchantAmount: BigNumberish;
    agents: AddressLike[];
    agentFees: BigNumberish[];
    platformFee: BigNumberish;
    sessionId: BytesLike;
    isDisputed: boolean;
  };

  export type SplitConfigStructOutput = [
    merchantWallet: string,
    merchantAmount: bigint,
    agents: string[],
    agentFees: bigint[],
    platformFee: bigint,
    sessionId: string,
    isDisputed: boolean
  ] & {
    merchantWallet: string;
    merchantAmount: bigint;
    agents: string[];
    agentFees: bigint[];
    platformFee: bigint;
    sessionId: string;
    isDisputed: boolean;
  };
}

export interface IAgentPaymentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelIntent"
      | "createIntent"
      | "executeAutoSplit"
      | "executeIntent"
      | "getIntent"
      | "getPendingBalance"
      | "getSplitConfig"
      | "setSplitConfig"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IntentCancelled"
      | "IntentCreated"
      | "IntentExecuted"
      | "PaymentSplit"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelIntent",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createIntent",
    values: [AddressLike[], BigNumberish[], BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAutoSplit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeIntent",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingBalance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSplitConfig",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSplitConfig",
    values: [BytesLike, IAgentPayment.SplitConfigStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeAutoSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIntent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSplitConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSplitConfig",
    data: BytesLike
  ): Result;
}

export namespace IntentCancelledEvent {
  export type InputTuple = [
    intentId: BytesLike,
    canceller: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    intentId: string,
    canceller: string,
    reason: string
  ];
  export interface OutputObject {
    intentId: string;
    canceller: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentCreatedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    payer: AddressLike,
    totalAmount: BigNumberish,
    collaborationId: BytesLike
  ];
  export type OutputTuple = [
    intentId: string,
    payer: string,
    totalAmount: bigint,
    collaborationId: string
  ];
  export interface OutputObject {
    intentId: string;
    payer: string;
    totalAmount: bigint;
    collaborationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentExecutedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    totalAmount: BigNumberish,
    recipientCount: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    totalAmount: bigint,
    recipientCount: bigint
  ];
  export interface OutputObject {
    intentId: string;
    totalAmount: bigint;
    recipientCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSplitEvent {
  export type InputTuple = [
    intentId: BytesLike,
    sessionId: BytesLike,
    merchantWallet: AddressLike,
    merchantAmount: BigNumberish,
    agentFees: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    sessionId: string,
    merchantWallet: string,
    merchantAmount: bigint,
    agentFees: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    intentId: string;
    sessionId: string;
    merchantWallet: string;
    merchantAmount: bigint;
    agentFees: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAgentPayment extends BaseContract {
  connect(runner?: ContractRunner | null): IAgentPayment;
  waitForDeployment(): Promise<this>;

  interface: IAgentPaymentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelIntent: TypedContractMethod<
    [intentId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  createIntent: TypedContractMethod<
    [
      recipients: AddressLike[],
      amounts: BigNumberish[],
      collaborationId: BytesLike,
      expiresIn: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  executeAutoSplit: TypedContractMethod<
    [orderId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeIntent: TypedContractMethod<
    [intentId: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getIntent: TypedContractMethod<
    [intentId: BytesLike],
    [IAgentPayment.PaymentIntentStructOutput],
    "view"
  >;

  getPendingBalance: TypedContractMethod<
    [payee: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  getSplitConfig: TypedContractMethod<
    [orderId: BytesLike],
    [IAgentPayment.SplitConfigStructOutput],
    "view"
  >;

  setSplitConfig: TypedContractMethod<
    [orderId: BytesLike, config: IAgentPayment.SplitConfigStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createIntent"
  ): TypedContractMethod<
    [
      recipients: AddressLike[],
      amounts: BigNumberish[],
      collaborationId: BytesLike,
      expiresIn: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeAutoSplit"
  ): TypedContractMethod<
    [orderId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getIntent"
  ): TypedContractMethod<
    [intentId: BytesLike],
    [IAgentPayment.PaymentIntentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingBalance"
  ): TypedContractMethod<
    [payee: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSplitConfig"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [IAgentPayment.SplitConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "setSplitConfig"
  ): TypedContractMethod<
    [orderId: BytesLike, config: IAgentPayment.SplitConfigStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "IntentCancelled"
  ): TypedContractEvent<
    IntentCancelledEvent.InputTuple,
    IntentCancelledEvent.OutputTuple,
    IntentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "IntentCreated"
  ): TypedContractEvent<
    IntentCreatedEvent.InputTuple,
    IntentCreatedEvent.OutputTuple,
    IntentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "IntentExecuted"
  ): TypedContractEvent<
    IntentExecutedEvent.InputTuple,
    IntentExecutedEvent.OutputTuple,
    IntentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSplit"
  ): TypedContractEvent<
    PaymentSplitEvent.InputTuple,
    PaymentSplitEvent.OutputTuple,
    PaymentSplitEvent.OutputObject
  >;

  filters: {
    "IntentCancelled(bytes32,address,string)": TypedContractEvent<
      IntentCancelledEvent.InputTuple,
      IntentCancelledEvent.OutputTuple,
      IntentCancelledEvent.OutputObject
    >;
    IntentCancelled: TypedContractEvent<
      IntentCancelledEvent.InputTuple,
      IntentCancelledEvent.OutputTuple,
      IntentCancelledEvent.OutputObject
    >;

    "IntentCreated(bytes32,address,uint256,bytes32)": TypedContractEvent<
      IntentCreatedEvent.InputTuple,
      IntentCreatedEvent.OutputTuple,
      IntentCreatedEvent.OutputObject
    >;
    IntentCreated: TypedContractEvent<
      IntentCreatedEvent.InputTuple,
      IntentCreatedEvent.OutputTuple,
      IntentCreatedEvent.OutputObject
    >;

    "IntentExecuted(bytes32,uint256,uint256)": TypedContractEvent<
      IntentExecutedEvent.InputTuple,
      IntentExecutedEvent.OutputTuple,
      IntentExecutedEvent.OutputObject
    >;
    IntentExecuted: TypedContractEvent<
      IntentExecutedEvent.InputTuple,
      IntentExecutedEvent.OutputTuple,
      IntentExecutedEvent.OutputObject
    >;

    "PaymentSplit(bytes32,bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      PaymentSplitEvent.InputTuple,
      PaymentSplitEvent.OutputTuple,
      PaymentSplitEvent.OutputObject
    >;
    PaymentSplit: TypedContractEvent<
      PaymentSplitEvent.InputTuple,
      PaymentSplitEvent.OutputTuple,
      PaymentSplitEvent.OutputObject
    >;
  };
}
