/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ICollaboration {
  export type AgreementStruct = {
    agreementId: BytesLike;
    initiator: AddressLike;
    agentIds: BytesLike[];
    agentWallets: AddressLike[];
    shareRatios: BigNumberish[];
    validFrom: BigNumberish;
    validUntil: BigNumberish;
    termsHash: BytesLike;
    requiredApprovals: BigNumberish;
    currentApprovals: BigNumberish;
    status: BigNumberish;
  };

  export type AgreementStructOutput = [
    agreementId: string,
    initiator: string,
    agentIds: string[],
    agentWallets: string[],
    shareRatios: bigint[],
    validFrom: bigint,
    validUntil: bigint,
    termsHash: string,
    requiredApprovals: bigint,
    currentApprovals: bigint,
    status: bigint
  ] & {
    agreementId: string;
    initiator: string;
    agentIds: string[];
    agentWallets: string[];
    shareRatios: bigint[];
    validFrom: bigint;
    validUntil: bigint;
    termsHash: string;
    requiredApprovals: bigint;
    currentApprovals: bigint;
    status: bigint;
  };
}

export interface ICollaborationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveAgreement"
      | "calculateDistribution"
      | "createAgreement"
      | "createFromTemplate"
      | "createTemplate"
      | "distributeByAgreement"
      | "extendAgreement"
      | "getAgentAgreements"
      | "getAgreement"
      | "getAgreementStatus"
      | "hasApproved"
      | "isAgreementValid"
      | "terminateAgreement"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgreementActivated"
      | "AgreementApproved"
      | "AgreementCreated"
      | "AgreementTerminated"
      | "ShareDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveAgreement",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateDistribution",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [
      BytesLike[],
      AddressLike[],
      BigNumberish[],
      BigNumberish,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createFromTemplate",
    values: [BytesLike, BytesLike[], AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTemplate",
    values: [string, BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeByAgreement",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "extendAgreement",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentAgreements",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreementStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgreementValid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "terminateAgreement",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createFromTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeByAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentAgreements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgreementStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAgreementValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "terminateAgreement",
    data: BytesLike
  ): Result;
}

export namespace AgreementActivatedEvent {
  export type InputTuple = [agreementId: BytesLike, activatedAt: BigNumberish];
  export type OutputTuple = [agreementId: string, activatedAt: bigint];
  export interface OutputObject {
    agreementId: string;
    activatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementApprovedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    agentId: BytesLike,
    approver: AddressLike,
    currentApprovals: BigNumberish,
    requiredApprovals: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    agentId: string,
    approver: string,
    currentApprovals: bigint,
    requiredApprovals: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    agentId: string;
    approver: string;
    currentApprovals: bigint;
    requiredApprovals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementCreatedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    initiator: AddressLike,
    agentIds: BytesLike[],
    validUntil: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: string,
    initiator: string,
    agentIds: string[],
    validUntil: bigint
  ];
  export interface OutputObject {
    agreementId: string;
    initiator: string;
    agentIds: string[];
    validUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementTerminatedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    terminator: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    agreementId: string,
    terminator: string,
    reason: string
  ];
  export interface OutputObject {
    agreementId: string;
    terminator: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShareDistributedEvent {
  export type InputTuple = [
    agreementId: BytesLike,
    transactionId: BytesLike,
    totalAmount: BigNumberish,
    distributions: BigNumberish[]
  ];
  export type OutputTuple = [
    agreementId: string,
    transactionId: string,
    totalAmount: bigint,
    distributions: bigint[]
  ];
  export interface OutputObject {
    agreementId: string;
    transactionId: string;
    totalAmount: bigint;
    distributions: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ICollaboration extends BaseContract {
  connect(runner?: ContractRunner | null): ICollaboration;
  waitForDeployment(): Promise<this>;

  interface: ICollaborationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveAgreement: TypedContractMethod<
    [agreementId: BytesLike, agentId: BytesLike],
    [void],
    "nonpayable"
  >;

  calculateDistribution: TypedContractMethod<
    [agreementId: BytesLike, totalAmount: BigNumberish],
    [bigint[]],
    "view"
  >;

  createAgreement: TypedContractMethod<
    [
      agentIds: BytesLike[],
      agentWallets: AddressLike[],
      shareRatios: BigNumberish[],
      validUntil: BigNumberish,
      termsHash: BytesLike,
      requiredApprovals: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  createFromTemplate: TypedContractMethod<
    [
      templateId: BytesLike,
      agentIds: BytesLike[],
      agentWallets: AddressLike[],
      validUntil: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  createTemplate: TypedContractMethod<
    [name: string, defaultRatios: BigNumberish[], termsHash: BytesLike],
    [string],
    "nonpayable"
  >;

  distributeByAgreement: TypedContractMethod<
    [
      agreementId: BytesLike,
      totalAmount: BigNumberish,
      transactionId: BytesLike
    ],
    [bigint[]],
    "nonpayable"
  >;

  extendAgreement: TypedContractMethod<
    [agreementId: BytesLike, newValidUntil: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAgentAgreements: TypedContractMethod<
    [agentId: BytesLike],
    [string[]],
    "view"
  >;

  getAgreement: TypedContractMethod<
    [agreementId: BytesLike],
    [ICollaboration.AgreementStructOutput],
    "view"
  >;

  getAgreementStatus: TypedContractMethod<
    [agreementId: BytesLike],
    [bigint],
    "view"
  >;

  hasApproved: TypedContractMethod<
    [agreementId: BytesLike, approver: AddressLike],
    [boolean],
    "view"
  >;

  isAgreementValid: TypedContractMethod<
    [agreementId: BytesLike],
    [boolean],
    "view"
  >;

  terminateAgreement: TypedContractMethod<
    [agreementId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveAgreement"
  ): TypedContractMethod<
    [agreementId: BytesLike, agentId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateDistribution"
  ): TypedContractMethod<
    [agreementId: BytesLike, totalAmount: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [
      agentIds: BytesLike[],
      agentWallets: AddressLike[],
      shareRatios: BigNumberish[],
      validUntil: BigNumberish,
      termsHash: BytesLike,
      requiredApprovals: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createFromTemplate"
  ): TypedContractMethod<
    [
      templateId: BytesLike,
      agentIds: BytesLike[],
      agentWallets: AddressLike[],
      validUntil: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTemplate"
  ): TypedContractMethod<
    [name: string, defaultRatios: BigNumberish[], termsHash: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeByAgreement"
  ): TypedContractMethod<
    [
      agreementId: BytesLike,
      totalAmount: BigNumberish,
      transactionId: BytesLike
    ],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "extendAgreement"
  ): TypedContractMethod<
    [agreementId: BytesLike, newValidUntil: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgentAgreements"
  ): TypedContractMethod<[agentId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAgreement"
  ): TypedContractMethod<
    [agreementId: BytesLike],
    [ICollaboration.AgreementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgreementStatus"
  ): TypedContractMethod<[agreementId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<
    [agreementId: BytesLike, approver: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAgreementValid"
  ): TypedContractMethod<[agreementId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "terminateAgreement"
  ): TypedContractMethod<
    [agreementId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgreementActivated"
  ): TypedContractEvent<
    AgreementActivatedEvent.InputTuple,
    AgreementActivatedEvent.OutputTuple,
    AgreementActivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementApproved"
  ): TypedContractEvent<
    AgreementApprovedEvent.InputTuple,
    AgreementApprovedEvent.OutputTuple,
    AgreementApprovedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementCreated"
  ): TypedContractEvent<
    AgreementCreatedEvent.InputTuple,
    AgreementCreatedEvent.OutputTuple,
    AgreementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementTerminated"
  ): TypedContractEvent<
    AgreementTerminatedEvent.InputTuple,
    AgreementTerminatedEvent.OutputTuple,
    AgreementTerminatedEvent.OutputObject
  >;
  getEvent(
    key: "ShareDistributed"
  ): TypedContractEvent<
    ShareDistributedEvent.InputTuple,
    ShareDistributedEvent.OutputTuple,
    ShareDistributedEvent.OutputObject
  >;

  filters: {
    "AgreementActivated(bytes32,uint256)": TypedContractEvent<
      AgreementActivatedEvent.InputTuple,
      AgreementActivatedEvent.OutputTuple,
      AgreementActivatedEvent.OutputObject
    >;
    AgreementActivated: TypedContractEvent<
      AgreementActivatedEvent.InputTuple,
      AgreementActivatedEvent.OutputTuple,
      AgreementActivatedEvent.OutputObject
    >;

    "AgreementApproved(bytes32,bytes32,address,uint8,uint8)": TypedContractEvent<
      AgreementApprovedEvent.InputTuple,
      AgreementApprovedEvent.OutputTuple,
      AgreementApprovedEvent.OutputObject
    >;
    AgreementApproved: TypedContractEvent<
      AgreementApprovedEvent.InputTuple,
      AgreementApprovedEvent.OutputTuple,
      AgreementApprovedEvent.OutputObject
    >;

    "AgreementCreated(bytes32,address,bytes32[],uint256)": TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;
    AgreementCreated: TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;

    "AgreementTerminated(bytes32,address,string)": TypedContractEvent<
      AgreementTerminatedEvent.InputTuple,
      AgreementTerminatedEvent.OutputTuple,
      AgreementTerminatedEvent.OutputObject
    >;
    AgreementTerminated: TypedContractEvent<
      AgreementTerminatedEvent.InputTuple,
      AgreementTerminatedEvent.OutputTuple,
      AgreementTerminatedEvent.OutputObject
    >;

    "ShareDistributed(bytes32,bytes32,uint256,uint256[])": TypedContractEvent<
      ShareDistributedEvent.InputTuple,
      ShareDistributedEvent.OutputTuple,
      ShareDistributedEvent.OutputObject
    >;
    ShareDistributed: TypedContractEvent<
      ShareDistributedEvent.InputTuple,
      ShareDistributedEvent.OutputTuple,
      ShareDistributedEvent.OutputObject
    >;
  };
}
