import { useMemo, useState, useCallback, useEffect } from 'react';
import { AgentTemplate } from '../../../lib/api/agent-template.api';
import { useToast } from '../../../contexts/ToastContext';
import { agentTemplateApi } from '../../../lib/api/agent-template.api';
import { useRouter } from 'next/router';
import { useLocalization } from '../../../contexts/LocalizationContext';
import { WorkflowEditor, type WorkflowDefinition } from './WorkflowEditor';
import { AgentExportPanel } from './AgentExportPanel';
import { CapabilityAssembler, type AgentRole } from './CapabilityAssembler';
import { RuleTemplateSystem, type RuleTemplate } from './RuleTemplateSystem';

interface AgentGeneratorProps {
  selectedTemplate: AgentTemplate | null;
  onTemplateReset: () => void;
  isAuthenticated?: boolean;
}

const getSteps = (t: (msg: any) => string) => [
  { id: 'template', title: { zh: '选择模板', en: 'Choose Template' } },
  { id: 'config', title: { zh: '配置能力', en: 'Configure Capabilities' } },
  { id: 'workflow', title: { zh: '工作流编辑', en: 'Workflow Editor' } },
  { id: 'auth', title: { zh: '授权与支付', en: 'Authorization & Payment' } },
  { id: 'preview', title: { zh: '预览 & 发布', en: 'Preview & Deploy' } },
];

export function AgentGenerator({
  selectedTemplate,
  onTemplateReset,
  isAuthenticated = false,
}: AgentGeneratorProps) {
  const router = useRouter();
  const { success, error } = useToast();
  const { t } = useLocalization();
  const steps = getSteps(t);
  const [currentStep, setCurrentStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [showCodePreview, setShowCodePreview] = useState(false);
  const [generatedCode, setGeneratedCode] = useState<string>('');
  const [workflow, setWorkflow] = useState<any>(null);
  const [useAdvancedWorkflow, setUseAdvancedWorkflow] = useState(false);
  const [selectedRules, setSelectedRules] = useState<RuleTemplate[]>([]);
  const [showRules, setShowRules] = useState(false);
  const [form, setForm] = useState({
    name: '',
    description: '',
    targetUsers: '全球用户',
    tone: 'professional',
    agentType: 'user' as 'user' | 'merchant' | 'developer',
    capabilities: ['search', 'auto_pay'],
    quickPayLimit: 20,
    quickPayDaily: 200,
    payoutWallet: '',
    autoEarnEnabled: true,
    monitoringEnabled: true,
    publish: true,
  });
  const [createdAgentId, setCreatedAgentId] = useState<string | undefined>(undefined);

  // 根据模板自动设置Agent类型
  useEffect(() => {
    if (selectedTemplate) {
      const category = selectedTemplate.category?.toLowerCase() || '';
      if (category.includes('merchant') || category.includes('商户')) {
        setForm((prev) => ({ ...prev, agentType: 'merchant' }));
      } else if (category.includes('developer') || category.includes('开发')) {
        setForm((prev) => ({ ...prev, agentType: 'developer' }));
      } else {
        setForm((prev) => ({ ...prev, agentType: 'user' }));
      }
    }
  }, [selectedTemplate]);

  const canContinue = useMemo(() => {
    if (!selectedTemplate) return false;
    if (currentStep === 1) {
      return form.name.trim().length > 0 && form.description.trim().length > 0;
    }
    if (currentStep === 2) {
      return form.payoutWallet.trim().length > 0;
    }
    if (currentStep === 3) {
      // 工作流步骤：可选，允许跳过
      return true;
    }
    return true;
  }, [currentStep, form, selectedTemplate]);

  const handleToggleCapability = (capability: string) => {
    setForm((prev) => {
      const exists = prev.capabilities.includes(capability);
      return {
        ...prev,
        capabilities: exists
          ? prev.capabilities.filter((item) => item !== capability)
          : [...prev.capabilities, capability],
      };
    });
  };

  const proceedStep = () => {
    if (!canContinue) return;
    setCurrentStep((prev) => Math.min(prev + 1, steps.length));
  };

  const goBack = () => {
    setCurrentStep((prev) => Math.max(prev - 1, 1));
  };

  const generateCode = useCallback(() => {
    if (!selectedTemplate) return '';
    
    // 根据Agent类型生成不同的代码
    const agentType = form.agentType || 'user';
    let code = '';
    
    if (agentType === 'user') {
      code = `# ${form.name || 'My User Agent'}
# Generated by Agentrix Agent Builder - User Agent

import { AgentrixUserAgent } from '@agentrix/agent-sdk'

const agent = new AgentrixUserAgent({
  agentId: '${selectedTemplate.id}',
  apiKey: 'your-api-key',
  mode: 'user',
  capabilities: ${JSON.stringify(form.capabilities, null, 2)},
  settings: {
    quickPayLimit: ${form.quickPayLimit},
    quickPayDaily: ${form.quickPayDaily},
    autoEarnEnabled: ${form.autoEarnEnabled},
    features: {
      feeEstimation: true,
      riskAssessment: true,
      kycReuse: true,
      paymentMemory: true,
      subscriptions: true,
      budgetManagement: true,
      transactionClassification: true,
    }
  }
})

# 启动Agent
agent.start()

# User Agent功能：
# - 费用估算和风险评估
# - KYC状态查询和复用
# - 支付记忆和偏好管理
# - 订阅识别和管理
# - 预算设置和跟踪
# - 交易分类和分析`;
    } else if (agentType === 'merchant') {
      code = `# ${form.name || 'My Merchant Agent'}
# Generated by Agentrix Agent Builder - Merchant Agent

import { AgentrixMerchantAgent } from '@agentrix/agent-sdk'

const agent = new AgentrixMerchantAgent({
  agentId: '${selectedTemplate.id}',
  apiKey: 'your-api-key',
  mode: 'merchant',
  capabilities: ${JSON.stringify(form.capabilities, null, 2)},
  settings: {
    features: {
      webhookAutomation: true,
      autoFulfillment: true,
      multiChainAccounts: true,
      reconciliation: true,
      settlementRules: true,
    }
  }
})

# 启动Agent
agent.start()

# Merchant Agent功能：
# - Webhook自动化配置
# - 自动发货和履约
# - 多链账户管理
# - 自动对账
# - 结算规则配置`;
    } else {
      code = `# ${form.name || 'My Developer Agent'}
# Generated by Agentrix Agent Builder - Developer Agent

import { AgentrixDeveloperAgent } from '@agentrix/agent-sdk'

const agent = new AgentrixDeveloperAgent({
  agentId: '${selectedTemplate.id}',
  apiKey: 'your-api-key',
  mode: 'developer',
  capabilities: ${JSON.stringify(form.capabilities, null, 2)},
  settings: {
    features: {
      codeGeneration: true,
      apiDocumentation: true,
      sandboxTesting: true,
      sdkIntegration: true,
    }
  }
})

# 启动Agent
agent.start()

# Developer Agent功能：
# - API/SDK代码生成
# - 文档查询和示例
# - 沙箱测试环境
# - 集成支持`;
    }
    
    setGeneratedCode(code);
    return code;
  }, [selectedTemplate, form]);

  const handlePreview = () => {
    const code = generateCode();
    setShowCodePreview(true);
  };

  const handleDeploy = async () => {
    if (!isAuthenticated) {
      error(t({ zh: '请先登录后再部署 Agent', en: 'Please login before deploying Agent' }));
      return;
    }
    if (!selectedTemplate) {
      error(t({ zh: '请先选择一个模板', en: 'Please select a template first' }));
      return;
    }
    if (!form.name || !form.description) {
      error(t({ zh: '请填写 Agent 名称和描述', en: 'Please fill in Agent name and description' }));
      return;
    }
    setLoading(true);
    try {
      console.log('🚀 开始部署Agent，模板ID:', selectedTemplate.id);
      console.log('📋 表单数据:', form);
      
      // 先生成Agent实例
      const payload = {
        name: form.name,
        description: form.description,
        publish: true, // 部署时自动发布
        settings: {
          targetUsers: form.targetUsers,
          tone: form.tone,
          capabilities: form.capabilities,
          limits: {
            quickPay: {
              single: form.quickPayLimit,
              daily: form.quickPayDaily,
            },
          },
          payoutWallet: form.payoutWallet,
          autoEarnEnabled: form.autoEarnEnabled,
          monitoringEnabled: form.monitoringEnabled,
          workflow, // 包含工作流定义
        },
      };
      
      console.log('📤 发送请求，payload:', JSON.stringify(payload, null, 2));
      
      // 创建Agent实例
      const instance = await agentTemplateApi.instantiateTemplate(selectedTemplate.id, payload);
      
      console.log('✅ Agent实例创建成功:', instance);
      
      // 保存创建的Agent ID，用于导出功能
      const agentId = instance?.id || '';
      if (agentId) {
        setCreatedAgentId(agentId);
      }
      
      // 如果Agent创建成功，更新状态为active（部署）
      if (instance && instance.id) {
        try {
          const { userAgentApi } = await import('../../../lib/api/user-agent.api');
          console.log('🔄 尝试更新Agent状态为active...');
          // 注意：toggleStatus可能需要不同的参数格式，这里先注释掉，避免错误
          // await userAgentApi.toggleStatus(instance.id, 'active');
          console.log('✅ Agent状态更新成功');
        } catch (statusError) {
          console.warn('⚠️ 更新Agent状态失败，但Agent已创建:', statusError);
        }
      }
      
      success(t({ zh: '🎉 Agent已生成并部署成功！', en: '🎉 Agent generated and deployed successfully!' }));
      
      // 显示成功消息并跳转到Agent工作台
      // 确保 instance.id 存在，如果不存在则跳转到工作台首页
      setTimeout(() => {
        if (agentId) {
          router.push(`/agent-enhanced?agentId=${agentId}`);
        } else {
          // 如果没有 agentId，跳转到工作台首页
          router.push('/agent-enhanced');
        }
      }, 1000);
    } catch (err: any) {
      console.error('❌ 部署Agent失败:', err);
      console.error('错误详情:', {
        message: err.message,
        stack: err.stack,
        response: err.response?.data,
        status: err.response?.status,
      });
      
      // 如果是未授权错误，提示登录
      if (err.message?.includes('401') || err.message?.includes('Unauthorized') || err.response?.status === 401) {
        error(t({ zh: '请先登录后再部署 Agent', en: 'Please login before deploying Agent' }));
      } else if (err.response?.status === 404) {
        error(t({ zh: '模板不存在或已被删除', en: 'Template not found or deleted' }));
      } else if (err.response?.status === 400) {
        error(t({ zh: '请求参数错误：' + (err.response?.data?.message || err.message), en: 'Invalid request: ' + (err.response?.data?.message || err.message) }));
      } else {
        error(err.response?.data?.message || err.message || t({ zh: '部署失败，请稍后再试', en: 'Deployment failed, please try again' }));
      }
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async () => {
    if (!isAuthenticated) {
      error(t({ zh: '请先登录后再生成 Agent', en: 'Please login before generating Agent' }));
      return;
    }
    if (!selectedTemplate) {
      error(t({ zh: '请先选择一个模板', en: 'Please select a template first' }));
      return;
    }
    if (!form.name || !form.description) {
      error(t({ zh: '请填写 Agent 名称和描述', en: 'Please fill in Agent name and description' }));
      return;
    }
    setLoading(true);
    try {
      console.log('🚀 开始生成Agent，模板ID:', selectedTemplate.id);
      console.log('📋 表单数据:', form);
      
      const payload = {
        name: form.name,
        description: form.description,
        publish: form.publish,
        settings: {
          targetUsers: form.targetUsers,
          tone: form.tone,
          capabilities: form.capabilities,
          limits: {
            quickPay: {
              single: form.quickPayLimit,
              daily: form.quickPayDaily,
            },
          },
          payoutWallet: form.payoutWallet,
          autoEarnEnabled: form.autoEarnEnabled,
          monitoringEnabled: form.monitoringEnabled,
          workflow, // 包含工作流定义
        },
      };
      
      console.log('📤 发送请求，payload:', JSON.stringify(payload, null, 2));
      
      const instance = await agentTemplateApi.instantiateTemplate(selectedTemplate.id, payload);
      
      console.log('✅ Agent实例创建成功:', instance);
      
      success(t({ zh: '🎉 Agent已生成并部署成功！正在跳转到工作台...', en: '🎉 Agent generated and deployed successfully! Redirecting to workspace...' }));
      
      // 显示成功提示并跳转到Agent工作台
      if (instance && instance.id) {
        setTimeout(() => {
          router.push(`/agent-enhanced?agentId=${instance.id}`);
        }, 1500);
      }
    } catch (err: any) {
      console.error('❌ 生成Agent失败:', err);
      console.error('错误详情:', {
        message: err.message,
        stack: err.stack,
        response: err.response?.data,
        status: err.response?.status,
      });
      
      // 如果是未授权错误，提示登录
      if (err.message?.includes('401') || err.message?.includes('Unauthorized') || err.response?.status === 401) {
        error(t({ zh: '请先登录后再生成 Agent', en: 'Please login before generating Agent' }));
      } else if (err.response?.status === 404) {
        error(t({ zh: '模板不存在或已被删除', en: 'Template not found or deleted' }));
      } else if (err.response?.status === 400) {
        error(t({ zh: '请求参数错误：' + (err.response?.data?.message || err.message), en: 'Invalid request: ' + (err.response?.data?.message || err.message) }));
      } else {
        error(err.response?.data?.message || err.message || t({ zh: '生成 Agent 失败，请稍后再试', en: 'Failed to generate Agent, please try again' }));
      }
    } finally {
      setLoading(false);
    }
  };

  if (!selectedTemplate) {
    return (
      <div className="text-center py-16 text-gray-500">
        {t({ zh: '请先从左侧选择一个模板开始', en: 'Please select a template from the left to start' })}
      </div>
    );
  }

  return (
    <div className="bg-white rounded-3xl shadow-xl border border-gray-100 p-8 space-y-8">
      {/* Step Indicator */}
      <div className="flex items-center justify-between">
        {steps.map((step, index) => (
          <div key={step.id} className="flex-1 flex items-center">
            <div
              className={`flex items-center justify-center w-10 h-10 rounded-full border-2 font-semibold ${
                currentStep >= index + 1
                  ? 'bg-blue-600 border-blue-600 text-white'
                  : 'border-gray-200 text-gray-400'
              }`}
            >
              {index + 1}
            </div>
            <div className="ml-3">
              <p className="text-xs text-gray-400 uppercase tracking-wide">{`Step ${index + 1}`}</p>
              <p className="text-sm font-semibold text-gray-800">{t(step.title)}</p>
            </div>
            {index < steps.length - 1 && (
              <div className="flex-1 h-px bg-gradient-to-r from-gray-200 to-transparent mx-3" />
            )}
          </div>
        ))}
      </div>

      {/* Step content */}
      {currentStep === 1 && (
        <div className="space-y-6">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-sm font-semibold text-gray-500 uppercase tracking-wide">
                模板已选择
              </p>
              <h3 className="text-2xl font-bold text-gray-900">{selectedTemplate.name}</h3>
              <p className="text-gray-500 mt-2 max-w-2xl">{selectedTemplate.description}</p>
            </div>
            <button
              onClick={onTemplateReset}
              className="text-sm text-blue-600 hover:text-blue-700 font-semibold"
            >
              重新选择
            </button>
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <label className="text-sm font-medium text-gray-700 mb-1 block">
                {t({ zh: 'Agent 名称', en: 'Agent Name' })}
              </label>
              <input
                type="text"
                value={form.name}
                onChange={(e) => setForm((prev) => ({ ...prev, name: e.target.value }))}
                placeholder={t({ zh: '例如：Auto-Earn 捕获者、小二 AI、Launchpad 助手', en: 'e.g.: Auto-Earn Catcher, Assistant AI, Launchpad Helper' })}
                className="w-full rounded-xl border border-gray-200 px-4 py-3 text-gray-900 bg-white focus:border-blue-500 focus:ring-2 focus:ring-blue-100 placeholder:text-gray-400"
              />
            </div>
            <div>
              <label className="text-sm font-medium text-gray-700 mb-1 block">
                {t({ zh: '面向人群 / Persona', en: 'Target Users / Persona' })}
              </label>
              <input
                type="text"
                value={form.targetUsers}
                onChange={(e) => setForm((prev) => ({ ...prev, targetUsers: e.target.value }))}
                className="w-full rounded-xl border border-gray-200 px-4 py-3 text-gray-900 bg-white focus:border-blue-500 focus:ring-2 focus:ring-blue-100 placeholder:text-gray-400"
              />
            </div>
          </div>

          <div>
            <label className="text-sm font-medium text-gray-700 mb-1 block">{t({ zh: '介绍 / 价值主张', en: 'Description / Value Proposition' })}</label>
            <textarea
              rows={3}
              value={form.description}
              onChange={(e) => setForm((prev) => ({ ...prev, description: e.target.value }))}
              className="w-full rounded-2xl border border-gray-200 px-4 py-3 text-gray-900 bg-white focus:border-blue-500 focus:ring-2 focus:ring-blue-100 placeholder:text-gray-400"
            />
          </div>
        </div>
      )}

      {currentStep === 2 && (
        <div className="grid md:grid-cols-2 gap-8">
          <div>
            <h4 className="text-lg font-semibold text-gray-900 mb-3">核心能力</h4>
            <div className="space-y-3">
              {[
                { id: 'search', label: 'AI 聚合搜索 / 比价' },
                { id: 'auto_pay', label: 'SmartPay / QuickPay' },
                { id: 'auto_task', label: '自动任务 / Auto-Earn' },
                { id: 'workflow', label: '多步骤 Workflow / Co-Routine' },
              ].map((cap) => (
                <label
                  key={cap.id}
                  className="flex items-center space-x-3 bg-gray-50 rounded-2xl px-4 py-3 cursor-pointer border border-transparent hover:border-gray-200"
                >
                  <input
                    type="checkbox"
                    checked={form.capabilities.includes(cap.id)}
                    onChange={() => handleToggleCapability(cap.id)}
                    className="w-4 h-4 text-blue-600 rounded"
                  />
                  <span className="text-sm font-medium text-gray-700">{t(cap.label)}</span>
                </label>
              ))}
            </div>
          </div>
          <div>
            <h4 className="text-lg font-semibold text-gray-900 mb-3">支付 & 限额</h4>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-sm text-gray-500">QuickPay 单笔阈值 (USDC)</label>
                <input
                  type="number"
                  min={1}
                  value={form.quickPayLimit}
                  onChange={(e) =>
                    setForm((prev) => ({ ...prev, quickPayLimit: Number(e.target.value) }))
                  }
                  className="w-full rounded-xl border border-gray-200 px-4 py-2 text-gray-900 bg-white focus:border-blue-500 focus:ring-2 focus:ring-blue-100 placeholder:text-gray-400"
                />
              </div>
              <div>
                <label className="text-sm text-gray-500">每日阈值 (USDC)</label>
                <input
                  type="number"
                  min={1}
                  value={form.quickPayDaily}
                  onChange={(e) =>
                    setForm((prev) => ({ ...prev, quickPayDaily: Number(e.target.value) }))
                  }
                  className="w-full rounded-xl border border-gray-200 px-4 py-2 text-gray-900 bg-white focus:border-blue-500 focus:ring-2 focus:ring-blue-100 placeholder:text-gray-400"
                />
              </div>
            </div>
            <div className="mt-4">
              <label className="text-sm text-gray-500">收益收款地址（钱包或法币账户）</label>
              <input
                type="text"
                value={form.payoutWallet}
                onChange={(e) => setForm((prev) => ({ ...prev, payoutWallet: e.target.value }))}
                placeholder="0x / Solana 地址，或 Stripe Account ID"
                className="w-full rounded-xl border border-gray-200 px-4 py-2 text-gray-900 bg-white focus:border-blue-500 focus:ring-2 focus:ring-blue-100 placeholder:text-gray-400"
              />
            </div>
            <div className="mt-4 flex items-center space-x-3">
              <label className="flex items-center space-x-2">
                <input
                  type="checkbox"
                  checked={form.autoEarnEnabled}
                  onChange={(e) =>
                    setForm((prev) => ({ ...prev, autoEarnEnabled: e.target.checked }))
                  }
                />
                <span className="text-sm text-gray-600">启用 Auto-Earn / 任务自动执行</span>
              </label>
            </div>
          </div>
        </div>
      )}

      {currentStep === 3 && (
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <div>
              <h4 className="text-lg font-semibold text-gray-900 mb-2">
                {t({ zh: '能力装配', en: 'Capability Assembly' })}
              </h4>
              <p className="text-sm text-gray-600">
                {t({ 
                  zh: '通过勾选能力模块来装配您的 Agent。Core 能力是必选的，Advanced 能力是可选的增强功能。', 
                  en: 'Assemble your Agent by selecting capability modules. Core capabilities are required, Advanced are optional.' 
                })}
              </p>
            </div>
            <button
              onClick={() => setUseAdvancedWorkflow(!useAdvancedWorkflow)}
              className="text-sm text-blue-600 hover:text-blue-700 font-medium"
            >
              {useAdvancedWorkflow 
                ? t({ zh: '切换到表单模式', en: 'Switch to Form Mode' })
                : t({ zh: '切换到高级工作流编辑器', en: 'Switch to Advanced Workflow Editor' })
              }
            </button>
          </div>

          {!useAdvancedWorkflow ? (
            // 表单式能力装配（默认模式）
            <div className="border border-gray-200 rounded-2xl p-6 bg-white">
              <CapabilityAssembler
                role={form.agentType}
                selectedCapabilities={form.capabilities}
                onCapabilitiesChange={(capabilities) => {
                  setForm((prev) => ({ ...prev, capabilities }));
                }}
              />
            </div>
          ) : (
            // 高级工作流编辑器（高级模式）
            <div className="h-[600px] border border-gray-200 rounded-2xl overflow-hidden">
              <div className="mb-4 p-4 bg-yellow-50 border-b border-yellow-200">
                <p className="text-sm text-yellow-800">
                  {t({ 
                    zh: '💡 高级模式：通过拖拽节点来构建复杂的工作流程。适合需要精细控制流程的高级用户。', 
                    en: '💡 Advanced Mode: Build complex workflows by dragging nodes. Suitable for advanced users who need fine-grained control.' 
                  })}
                </p>
              </div>
              <div className="h-[calc(100%-80px)]">
                <WorkflowEditor
                  workflow={workflow}
                  capabilities={form.capabilities}
                  onWorkflowChange={(wf) => setWorkflow(wf)}
                  onSave={(wf) => {
                    setWorkflow(wf);
                    success(t({ zh: '工作流已保存', en: 'Workflow saved' }));
                  }}
                  onImportFromCapabilities={(caps) => {
                    // 将能力列表转换为工作流
                    const nodes = caps.map((cap, index) => ({
                      id: `cap_${cap}_${index}`,
                      type: 'action' as const,
                      position: { x: 100 + (index % 3) * 200, y: 100 + Math.floor(index / 3) * 150 },
                      data: { label: cap, config: { actionType: 'capability', capabilityId: cap } },
                    }));
                    const edges = nodes.slice(0, -1).map((node, index) => ({
                      id: `edge_${index}`,
                      source: node.id,
                      target: nodes[index + 1].id,
                      condition: 'success',
                    }));
                    return { version: '1.0', nodes, edges };
                  }}
                />
              </div>
            </div>
          )}
        </div>
      )}

      {currentStep === 4 && (
        <div className="grid md:grid-cols-2 gap-8">
          <div className="space-y-4">
            <h4 className="text-lg font-semibold text-gray-900 mb-2">授权配置</h4>
            <div className="bg-gray-50 rounded-2xl p-4 border border-gray-100">
              <p className="text-sm text-gray-600">
                Builder 会为您的 Agent 自动配置接入 Agentrix 支付、数据、任务执行权限。若您
                已通过 KYC，系统会同步 QuickPay 白名单。
              </p>
            </div>
            <label className="flex items-center space-x-3">
              <input
                type="checkbox"
                checked={form.monitoringEnabled}
                onChange={(e) =>
                  setForm((prev) => ({ ...prev, monitoringEnabled: e.target.checked }))
                }
              />
              <span className="text-sm text-gray-600">
                同步启用 Agent 运行监控 / 报表（推荐）
              </span>
            </label>
          </div>
          <div className="space-y-4">
            <h4 className="text-lg font-semibold text-gray-900 mb-2">发布选项</h4>
            <label className="flex items-center space-x-3">
              <input
                type="checkbox"
                checked={form.publish}
                onChange={(e) => setForm((prev) => ({ ...prev, publish: e.target.checked }))}
              />
              <span className="text-sm text-gray-600">生成后立即上线（可随时暂停）</span>
            </label>
            <p className="text-xs text-gray-400">
              如果暂不发布，Agent 会保持草稿状态，可在“我的 Agent”列表里继续配置和接收推广链接。
            </p>
          </div>
        </div>
      )}

      {currentStep === 4 && (
        <div className="space-y-6">
          <div className="bg-gray-50 rounded-3xl border border-gray-100 p-6 space-y-4">
            <h4 className="text-xl font-semibold text-gray-900">{t({ zh: '生成摘要', en: 'Generation Summary' })}</h4>
            <ul className="space-y-3 text-sm text-gray-700">
              <li>
                <strong className="text-gray-900">{t({ zh: '名称', en: 'Name' })}：</strong>
                {form.name}
              </li>
              <li>
                <strong className="text-gray-900">{t({ zh: '模板', en: 'Template' })}：</strong>
                {selectedTemplate.name}
              </li>
              <li>
                <strong className="text-gray-900">{t({ zh: '核心能力', en: 'Core Capabilities' })}：</strong>
                {form.capabilities.join(' / ')}
              </li>
              <li>
                <strong className="text-gray-900">QuickPay {t({ zh: '限额', en: 'Limits' })}：</strong>
                {form.quickPayLimit} USDC / {t({ zh: '单笔', en: 'Single' })} · {form.quickPayDaily} USDC / {t({ zh: '日', en: 'Day' })}
              </li>
              <li>
                <strong className="text-gray-900">{t({ zh: '收益账户', en: 'Payout Wallet' })}：</strong>
                {form.payoutWallet}
              </li>
              <li>
                <strong className="text-gray-900">Auto-Earn：</strong>
                {form.autoEarnEnabled ? t({ zh: '已启用', en: 'Enabled' }) : t({ zh: '关闭', en: 'Disabled' })}
              </li>
            </ul>
          </div>

          {/* 代码预览 */}
          <div className="bg-slate-900 rounded-2xl border border-slate-700 p-6 space-y-4">
            <div className="flex items-center justify-between">
              <h4 className="text-lg font-semibold text-white">{t({ zh: '代码预览', en: 'Code Preview' })}</h4>
              <div className="flex space-x-2">
                <button
                  onClick={() => {
                    const code = generateCode()
                    navigator.clipboard.writeText(code)
                    success(t({ zh: '代码已复制到剪贴板', en: 'Code copied to clipboard' }))
                  }}
                  className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-700 transition-colors"
                >
                  {t({ zh: '复制代码', en: 'Copy Code' })}
                </button>
                <button
                  onClick={() => {
                    const code = generateCode()
                    const blob = new Blob([code], { type: 'text/plain' })
                    const url = URL.createObjectURL(blob)
                    const a = document.createElement('a')
                    a.href = url
                    a.download = `${form.name || 'agent'}.py`
                    a.click()
                    URL.revokeObjectURL(url)
                    success(t({ zh: '代码已下载', en: 'Code downloaded' }))
                  }}
                  className="px-4 py-2 bg-green-600 text-white rounded-lg text-sm hover:bg-green-700 transition-colors"
                >
                  {t({ zh: '下载代码', en: 'Download Code' })}
                </button>
              </div>
            </div>
            <div className="bg-slate-950 rounded-lg p-4 overflow-x-auto">
              <pre className="text-green-400 text-sm font-mono whitespace-pre-wrap">
                {generatedCode || generateCode()}
              </pre>
            </div>
          </div>

          {/* Agent导出功能 */}
          <div className="bg-white rounded-2xl border border-gray-200 p-6">
            <AgentExportPanel
              agentId={createdAgentId} // 使用创建的Agent ID
              agentName={form.name}
              agentType={form.agentType}
              workflow={workflow}
              form={form}
              onExport={(exportType, platform) => {
                console.log('导出Agent:', { exportType, platform });
                success(t({ zh: '导出包已生成', en: 'Export package generated' }));
              }}
            />
          </div>

          {/* 部署选项 */}
          <div className="bg-blue-50 rounded-2xl border border-blue-100 p-6 space-y-4">
            <h4 className="text-lg font-semibold text-gray-900">{t({ zh: '部署选项', en: 'Deployment Options' })}</h4>
            <div className="space-y-3">
              <div className="flex items-center space-x-3">
                <input
                  type="checkbox"
                  checked={form.publish}
                  onChange={(e) => setForm((prev) => ({ ...prev, publish: e.target.checked }))}
                  className="w-4 h-4 text-blue-600 rounded"
                />
                <span className="text-sm text-gray-700">
                  {t({ zh: '生成后立即上线（可随时暂停）', en: 'Publish immediately after generation (can pause anytime)' })}
                </span>
              </div>
              <p className="text-xs text-gray-500">
                {t({
                  zh: '如果暂不发布，Agent会保持草稿状态，可在"我的Agent"列表里继续配置和接收推广链接。',
                  en: 'If not published, Agent will remain in draft status and can be configured and receive promotion links in "My Agents" list.',
                })}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Actions */}
      <div className="flex items-center justify-between">
          <button
            onClick={goBack}
            disabled={currentStep === 1 || loading}
            className="px-4 py-2 rounded-xl text-sm font-semibold text-gray-600 hover:text-gray-900 disabled:opacity-40"
          >
            {t({ zh: '上一步', en: 'Previous' })}
          </button>
          {currentStep < steps.length && (
            <button
              onClick={proceedStep}
              disabled={!canContinue || loading}
              className="px-6 py-3 rounded-2xl bg-blue-600 text-white text-sm font-semibold shadow-lg shadow-blue-200 disabled:opacity-50"
            >
              {t({ zh: '下一步', en: 'Next' })}
            </button>
          )}
          {currentStep === steps.length && (
            <div className="flex space-x-3">
              <button
                onClick={handleDeploy}
                disabled={loading}
                className="px-6 py-3 rounded-2xl bg-green-600 text-white text-sm font-semibold shadow-lg shadow-green-200 disabled:opacity-50 hover:bg-green-700 transition-colors"
              >
                {loading ? t({ zh: '部署中...', en: 'Deploying...' }) : t({ zh: '一键部署', en: 'Deploy Now' })}
              </button>
              <button
                onClick={handleSubmit}
                disabled={loading}
                className="px-6 py-3 rounded-2xl bg-gradient-to-r from-blue-600 to-indigo-600 text-white text-sm font-semibold shadow-lg shadow-blue-200 disabled:opacity-50"
              >
                {loading ? t({ zh: '生成中...', en: 'Generating...' }) : t({ zh: '一键生成我的 Agent', en: 'Generate My Agent' })}
              </button>
            </div>
          )}
      </div>
    </div>
  );
}

