name: Build iOS Simulator

on:
  push:
    branches: [main, master, build*]
  workflow_dispatch:

jobs:
  build-ios-simulator:
    uses: ./.github/workflows/build-ios-simulator.yml
    secrets: inherit